Open-Systems-Pharmacology/MoBi

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.Assets/packages.config
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.BatchTool/packages.config
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Core/packages.config
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/packages.config
src/MoBi.UI/MoBi.UI.csproj
src/MoBi.UI/packages.config
src/MoBi/MoBi.csproj
src/MoBi/packages.config
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.Tests/packages.config
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
tests/MoBi.UI.Tests/packages.config

Reverts Open-Systems-Pharmacology/MoBi#57

Revert "Fixes #55 update nuget packages"

---

appveyor-nightly.yml

adding package source for nightly build

Fixes #63 - Cannot import observed data

---

src/MoBi.UI/Diagram/DiagramManagers/MoBiReactionDiagramManager.cs
tests/MoBi.UI.Tests/Diagram/MoBiReactionDiagramManagerSpecs.cs
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Adding the override for Create. That was missed for this particular diagram manager

Fixes #79 - Exception error after Reaction commit to building block

---

SolutionInfo.cs
appveyor.yml
rakefile.rb
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.BatchTool/packages.config
src/MoBi.UI/MoBi.UI.csproj
src/MoBi.UI/packages.config
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
tests/MoBi.UI.Tests/packages.config

version numbers and update Databinding.DevExpress

Update version numbers

---

SolutionInfo.cs
appveyor.yml
rakefile.rb
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.BatchTool/packages.config
src/MoBi.UI/MoBi.UI.csproj
src/MoBi.UI/packages.config
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
tests/MoBi.UI.Tests/packages.config

* update version to 7.2.0
* update version to 7.2.0

Update version numbers (#97)

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.Assets/packages.config
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.BatchTool/packages.config
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Core/packages.config
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/packages.config
src/MoBi.UI/MoBi.UI.csproj
src/MoBi.UI/packages.config
src/MoBi/MoBi.csproj
src/MoBi/packages.config
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.Tests/packages.config
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
tests/MoBi.UI.Tests/packages.config

Core update to add fix to MoBi

Fixes #67 - Time Profile plots are missing lines

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.Assets/packages.config
src/MoBi.BatchTool/App.config
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.BatchTool/packages.config
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Core/app.config
src/MoBi.Core/packages.config
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/Presenter/SimulationChartPresenter.cs
src/MoBi.Presentation/app.config
src/MoBi.Presentation/packages.config
src/MoBi.UI/MoBi.UI.csproj
src/MoBi.UI/app.config
src/MoBi.UI/packages.config
src/MoBi/MoBi.csproj
src/MoBi/app.config
src/MoBi/packages.config
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.Tests/Presentation/Tasks/ObservedDataTasksSpecs.cs
tests/MoBi.Tests/app.config
tests/MoBi.Tests/packages.config
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
tests/MoBi.UI.Tests/app.config
tests/MoBi.UI.Tests/packages.config

Also updating Core components and DevExpress

Fixes #105 - Use CurveNamer to name chart curves

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.Assets/packages.config
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.BatchTool/packages.config
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Core/Serialization/Converter/IMoBiObjectConverter.cs
src/MoBi.Core/Serialization/Converter/v3_1/Converter30To313.cs
src/MoBi.Core/Serialization/Converter/v3_2/Converter313To32.cs
src/MoBi.Core/Serialization/Converter/v3_3/Converter321To331.cs
src/MoBi.Core/Serialization/Converter/v3_4/Converter33To34.cs
src/MoBi.Core/Serialization/Converter/v3_5/Converter341To351.cs
src/MoBi.Core/Serialization/Converter/v3_6/Converter351To361.cs
src/MoBi.Core/Serialization/Converter/v6_0/Converter36To601.cs
src/MoBi.Core/Serialization/Converter/v6_1/Converter60To61.cs
src/MoBi.Core/Serialization/Converter/v6_2/Converter62To63.cs
src/MoBi.Core/Serialization/Converter/v7_1/Converter63To710.cs
src/MoBi.Core/Serialization/Xml/Services/XmlSerializationService.cs
src/MoBi.Core/packages.config
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/packages.config
src/MoBi.UI/MoBi.UI.csproj
src/MoBi.UI/packages.config
src/MoBi/MoBi.csproj
src/MoBi/packages.config
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.Tests/packages.config
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
tests/MoBi.UI.Tests/packages.config

Very similar to what happened in PKSim. We only throw the message if the conversion REALLY happened as opposed to every time that a version is being changed

Fixes #140 multiple conversion

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.Assets/packages.config
src/MoBi.BatchTool/App.config
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.BatchTool/packages.config
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Core/app.config
src/MoBi.Core/packages.config
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Engine/app.config
src/MoBi.Engine/packages.config
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/app.config
src/MoBi.Presentation/packages.config
src/MoBi.UI/MoBi.UI.csproj
src/MoBi.UI/app.config
src/MoBi.UI/packages.config
src/MoBi/MoBi.csproj
src/MoBi/app.config
src/MoBi/packages.config
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.Tests/app.config
tests/MoBi.Tests/packages.config
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
tests/MoBi.UI.Tests/app.config
tests/MoBi.UI.Tests/packages.config

Update to latest core

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #563 Update to latest OSPSuite.Core

Fixes #563 Update to latest OSPSuite.Core

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/Tasks/ObservedDataTask.cs
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.Tests/Presentation/Tasks/ObservedDataTasksSpecs.cs
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Updating dlls

---

src/MoBi.Engine/Sbml/ASTHandler.cs
tests/MoBi.Tests/Core/SBML/ReactionImporterSpecs.cs

Fixes #594 (Create aliases when loading reactions from SBML files)

594 create aliases when loading reactions from sbml files

---

src/MoBi.Core/Domain/UnitSystem/MoBiDimensionFactory.cs
src/MoBi.Engine/Sbml/CompartmentImporter.cs
src/MoBi.Engine/Sbml/ParameterImporter.cs
src/MoBi.Engine/Sbml/SpeciesImporter.cs
src/MoBi.Engine/Sbml/UnitDefinitionImporter.cs
tests/MoBi.Tests/Core/SBML/CompartmentImporterSpecs.cs
tests/MoBi.Tests/Core/SBML/UnitImporterSpecs.cs

Fixes #614 (Import volume from sbml file)

Setting volume from size

---

src/MoBi.Engine/Sbml/UnitDefinitionImporter.cs
tests/MoBi.Tests/Core/SBML/UnitImporterSpecs.cs

Fixes #618 (parse combined units when importing from sbml)

Parse combined units

---

src/MoBi.Engine/Sbml/UnitDefinitionImporter.cs
tests/MoBi.Tests/Core/SBML/SBMLTaskSpecs.cs
tests/MoBi.Tests/Core/SBML/UnitImporterSpecs.cs

Fixes #622 (Using scale properly when importing unit definitions from SBML Files)

622 newly defined units properly translate when importing from sbml files

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/Tasks/ObservedDataTask.cs
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

closes #666
closes #667 
closes #668

666 importing mol weight

---

src/MoBi.Engine/MoBi.Engine.csproj

@msevestre hehe I could not see the ident issue locally, but since I could see it in github, I edited it directly online. This should then do the trick.

fixing ident

---

src/MoBi.UI/MoBi.UI.csproj

683 old importer reference removed

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

687 updating nuget to latest importer state

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForObservedDataFolder.cs
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

715 dlls plugged in

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.UI/Views/SelectReferenceView.Designer.cs
src/MoBi.UI/Views/SelectReferenceView.cs
src/MoBi.UI/Views/SelectReferenceView.resx
src/MoBi.UI/Views/ValidationMessagesView.cs

@Yuri05 Just UI reorganization and follow our default principles for constants

741 local reference point

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/Presenter/ChartPresenter.cs
src/MoBi.Presentation/Presenter/ComparisonChartPresenter.cs
src/MoBi.Presentation/Presenter/SimulationChartPresenter.cs
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

807 output mappings not cleared

---

src/MoBi.Presentation/Presenter/ChartPresenter.cs
src/MoBi.Presentation/Presenter/SimulationChartPresenter.cs
tests/MoBi.Tests/Presentation/SimulationChartPresenterSpecs.cs

Fixes #799 Observed data Tab not refreshed after adding observed data to chart
Fixes #800 Observed data not automatically mapped

Observed data drag/drop to chart

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/Domain/Model/MoBiProject.cs
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuFactoryForBuildBlocks.cs
src/MoBi.Presentation/MenusAndBars/ContextMenus/RootContextMenuForExpressionProfileBuildingBlock.cs
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/Nodes/MoleculeTreeNode.cs
src/MoBi.Presentation/Nodes/RootNodeType.cs
src/MoBi.Presentation/Presenter/Main/BuildingBlockExplorerPresenter.cs
src/MoBi.Presentation/Tasks/Interaction/AbstractStartValuesTask.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTaskForPathAndValueEntity.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForExpressionProfileBuildingBlock.cs
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

There's no view or presenter yet, just the building block explorer entries

Fixes #820 individual serialization

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForIndividualBuildingBlock.cs
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/PresentationRegister.cs
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

The only thing missing is Adding a new individual. That will be covered by a separate issue because the only way to create a new one is from #783

Fixes #645 Individual Management

---

src/MoBi.Presentation/Presenter/EditSimulationPresenter.cs
tests/MoBi.Tests/Presentation/EditSimulationPresenterSpecs.cs

821 drag and drop same obs data on chart duplicates mapping

---

src/MoBi.Core/Domain/Model/MoBiSimulation.cs
src/MoBi.Presentation/Presenter/ChartPresenter.cs
src/MoBi.Presentation/Presenter/EditSimulationPresenter.cs
src/MoBi.Presentation/Presenter/SimulationChartPresenter.cs
tests/MoBi.Tests/Core/MoBiSimulationSpecs.cs

847 cannot delete observed data fixed

---

src/MoBi.Core/Domain/Extensions/BuildingBlockExtensions.cs
src/MoBi.Presentation/Mappers/ExpressionParameterToParameterStartValueMapper.cs
src/MoBi.Presentation/Mappers/ExpressionProfileToParameterStartValuesMapper.cs
src/MoBi.Presentation/MenusAndBars/ContextMenus/RootContextMenuForParameterStartValuesBuildingBlock.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTaskFor.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForExpressionProfileBuildingBlock.cs
src/MoBi.Presentation/UICommand/AddExpressionAsParameterStartValuesCommand.cs
tests/MoBi.Tests/Core/SBML/ReactionImporterSpecs.cs
tests/MoBi.Tests/Presentation/Mapper/ExpressionParameterToParameterStartValueMapperSpecs.cs
tests/MoBi.Tests/Presentation/Mapper/ExpressionProfileToParameterStartValuesMapperSpecs.cs

See the caption in the context menu for this feature.
The by now familiar look:

Fixes #841 Parameter Values import of expression profile PKML

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Core/Commands/UpdateSimulationConfigurationCommand.cs
src/MoBi.Presentation/DTO/ModuleConfigurationDTO.cs
src/MoBi.Presentation/Mappers/ModuleConfigurationDTOToModuleConfigurationMapper.cs
src/MoBi.Presentation/Nodes/TreeNodeFactory.cs
src/MoBi.Presentation/Presenter/ConfigureSimulationPresenter.cs
src/MoBi.Presentation/Presenter/ConfigureSimulationPresenterBase.cs
src/MoBi.Presentation/Presenter/CreateSimulationPresenter.cs
src/MoBi.Presentation/Presenter/EditIndividualAndExpressionConfigurationsPresenter.cs
src/MoBi.Presentation/Presenter/EditModuleConfigurationsPresenter.cs
src/MoBi.UI/Views/EditModuleConfigurationsView.Designer.cs
tests/MoBi.Tests/Presentation/CreateSimulationPresenterSpecs.cs

I was going to build all this into my tests and configure PR, but there's one issue that would stop you from really using this UI meanwhile so it needs to be included in OSMOSES as I work on the configure feature.

#946 Some small changes to layout and mapping a new module configuration

---

src/MoBi.Presentation/Presenter/EditModuleConfigurationsPresenter.cs
src/MoBi.Presentation/Views/IEditModuleConfigurationsView.cs
src/MoBi.UI/Views/EditModuleConfigurationsView.Designer.cs
src/MoBi.UI/Views/EditModuleConfigurationsView.cs
tests/MoBi.Tests/Presentation/EditModuleConfigurationsPresenterSpecs.cs

Those little up and down arrows up in the top right.

Fixes #959 create simulation add up and down arrows to emphasis that order matters

---

src/MoBi.Presentation/Presenter/ChartPresenter.cs
tests/MoBi.Tests/Presentation/SimulationChartPresenterSpecs.cs

#875 time column showing in chart although it should not

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Core/Services/OutputSchemaTask.cs
src/MoBi.Core/Services/SimulationConfigurationFactory.cs
src/MoBi.Presentation/Presenter/CreateSimulationConfigurationPresenter.cs
src/MoBi.Presentation/Tasks/SimulationUpdateTask.cs
src/MoBi.UI/Views/EditOutputSchemaView.Designer.cs
src/MoBi.UI/Views/EditOutputSchemaView.cs
tests/MoBi.Tests/Core/Service/SimulationConfigurationFactorySpecs.cs
tests/MoBi.Tests/Presentation/CreateSimulationConfigurationPresenterSpecs.cs

Fixes #1132 simulation settings should operate independently from the project

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Core/Commands/AddItemToReactionCommand.cs
src/MoBi.Core/Domain/UnitSystem/DimensionConverter.cs
src/MoBi.Core/Reporting/TEXBuilder/DataRepositoryTEXBuilder.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForMoleculeBuilder.cs
src/MoBi.Presentation/Tasks/SimulationRunner.cs
tests/MoBi.Tests/Core/Commands/AddReactionPartnerToEductCollectionSpecs.cs
tests/MoBi.Tests/Core/MolWeightConverterSpecs.cs
tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForMoleculeBuilderSpecs.cs
tests/MoBi.Tests/Presentation/Tasks/SimulationRunnerSpecs.cs

Fixes #1167 
Dumbest code trying to get the MW from the building block underneath  where we have a parameter in the simulation. Crazy

Fixes #1167. Remove the most disgraceful code possible

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/Commands/SetParentPathCommand.cs
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

update core to latest

---

src/MoBi.Presentation/MenusAndBars/ContextMenus/RootContextMenuForExpressionProfileBuildingBlock.cs
src/MoBi.Presentation/Presenter/Main/MenuAndToolBarPresenter.cs
src/MoBi.Presentation/Repositories/ButtonGroupRepository.cs
src/MoBi.Presentation/Repositories/MenuBarItemRepository.cs
src/MoBi.Presentation/UICommand/AddNewExpressionProfileBuildingBlock.cs

Fixes #1185
A button that shouldn't cause a command to be run, but it does

Fixes #1185 Add Expression Profile Button Not Implemented

---

src/MoBi.Presentation/Presenter/HierarchicalSpatialStructurePresenter.cs
tests/MoBi.Tests/Presentation/HierarchicalSpatialStructurePresenterSpecs.cs

Fixes #1177
Any time you add a new top container in a spatial structure, there's an exception thrown.

Fixes #1177 Error when loading an exported organ in a new module

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/Tasks/Edit/EditTaskForContainer.cs
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.Tests/Presentation/Tasks/EditTaskForContainerSpecs.cs
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #1196
When exporting a container with individual from a spatial structure, the distributed parameters were missing sub-parameters

Fixes #1196 Distributed parameters missing from imported container

---

src/MoBi.Core/Commands/AddTopContainerCommand.cs
src/MoBi.Core/Commands/RemoveContainerFromSpatialStructureCommand.cs
src/MoBi.Core/Services/AdjustFormulaVisitor.cs
src/MoBi.Presentation/Presenter/EditDistributedParameterPresenter.cs
src/MoBi.Presentation/Presenter/EditParametersInContainerPresenter.cs
src/MoBi.Presentation/Presenter/HierarchicalSpatialStructurePresenter.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTask.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTaskFor.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForBuilder.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForContainer.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForContainerBase.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForMoleculeBuilder.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForProjectPathAndValueEntityBuildingBlocks.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForSimulation.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForTopContainer.cs
src/MoBi.Presentation/Tasks/Interaction/StartValuesTask.cs
src/MoBi.Presentation/Tasks/ModuleLoader.cs
src/MoBi.Presentation/UICommand/AddExpressionAsParameterValuesCommand.cs
tests/MoBi.Tests/Core/AdjustFormulasVisitorSpecs.cs
tests/MoBi.Tests/Core/Commands/RemoveContainerFromSpatialStructureCommandSpecs.cs
tests/MoBi.Tests/Helpers/DomainHelperForSpecs.cs
tests/MoBi.Tests/Presentation/HierarchicalSpatialStructurePresenterSpecs.cs
tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForContainerSpecs.cs
tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForExpressionProfileBuildingBlockSpecs.cs
tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForMoleculeBuilderSpecs.cs
tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForTopContainerSpecs.cs
tests/MoBi.Tests/Presentation/Tasks/ModuleLoaderSpecs.cs

Fixes #1193
Fixes #1203
This was a huge mess of code duplication, defensive programming, not understanding who was calling what. Probably some of the very early code written in MoBi
This is still a mess, but less of a mess. Working to add neighborhoods not by "HAND" as before but using the tasks that is used typically .BEcause of the complex task hierarchy, i had to separate the code to have specific implementation

Fixes #1193

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuFactoryForNeighborhoods.cs
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #1208 
Just use core to fix the issues 

Fixes #1208 fraction unbound not found

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/DTO/ContainerDTO.cs
src/MoBi.Presentation/DTO/SpatialStructureDTO.cs
src/MoBi.Presentation/Mappers/SpatialStructureToSpatialStructureDTOMapper.cs
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/Presenter/CreateNeighborhoodBuilderPresenter.cs
src/MoBi.Presentation/Presenter/EditNeighborhoodBuilderPresenter.cs
src/MoBi.Presentation/Presenter/SelectContainerPresenter.cs
src/MoBi.Presentation/Presenter/SelectContanerInTreePresenter.cs
src/MoBi.Presentation/Presenter/SelectLocalisationPresenter.cs
src/MoBi.Presentation/Presenter/SelectNeighborPathPresenter.cs
src/MoBi.Presentation/Presenter/SelectObjectInTreePresenter.cs
src/MoBi.Presentation/Views/ISelectEntityInTreeView.cs
src/MoBi.UI/MoBi.UI.csproj
src/MoBi.UI/Views/EditNeighborhoodBuilderView.cs
src/MoBi.UI/Views/SelectEntityInTreeView.cs
src/MoBi.UI/Views/SelectLocalisationView.cs
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.Tests/Presentation/CreateNeighborhoodBuilderPresenterSpecs.cs
tests/MoBi.Tests/Presentation/EditNeighborhoodBuilderPresenterSpecs.cs
tests/MoBi.Tests/Presentation/SelectContainerInTreePresenterSpecs.cs
tests/MoBi.Tests/Presentation/SelectNeighborPathPresenterSpecs.cs
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #1194
Fixes #1195
When connecting neighborhoods, it should be possible to select paths from any module in the project. The treeview and presenter were already capable of displaying multiple top containers if they were created.
Also when selecting a new parent container for a container, you can select from any level of the spatial structure

Fixes #1194 When selecting neighbors use all spatial structures in the project

---

src/MoBi.Presentation/Tasks/Edit/EditTaskForContainer.cs
tests/MoBi.Tests/Presentation/EditDistributedParameterPresenterSpecs.cs
tests/MoBi.Tests/Presentation/Tasks/EditTaskForContainerSpecs.cs

Fixes #1223
We have to handle Percentile parameters a little differently when exporting DistributedParameters.
Let's agree that this is the approach to take first. If acceptable I'll add the required unit tests.

Fixes #1223 Wrong values for distributed parameters

---

src/MoBi.UI/Views/SelectSpatialStructureAndMoleculesView.Designer.cs
src/MoBi.UI/Views/SelectSpatialStructureAndMoleculesView.cs

Fixes #1241
Some UI changes to the dialog box and grid

Fixes #1241 Extend initial conditions modal dialog changes

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/Presenter/ParameterValuesPresenter.cs
src/MoBi.Presentation/Presenter/PathAndValueModuleBuildingBlockPresenter.cs
src/MoBi.Presentation/Repositories/MenuBarItemRepository.cs
src/MoBi.Presentation/Tasks/Interaction/IStartValuesTask.cs
src/MoBi.Presentation/Tasks/Interaction/InitialConditionsTask.cs
src/MoBi.Presentation/Tasks/Interaction/ParameterValuesTask.cs
src/MoBi.Presentation/Tasks/Interaction/StartValuesTask.cs
src/MoBi.Presentation/UICommand/ParameterValuesExtendUICommand.cs
src/MoBi.UI/MoBi.UI.csproj
src/MoBi.UI/Views/BasePathAndValueEntityView.cs
src/MoBi.UI/Views/InitialConditionsView.cs
src/MoBi.UI/Views/ParameterValuesView.cs
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.Tests/Presentation/Tasks/ParameterValuesTaskSpecs.cs
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #1245 
Allow users to add parameter values from selected spatial structure and molecules

Extend parameter values building block

---

src/MoBi.Core/Domain/Model/MoBiSimulation.cs
src/MoBi.Core/Domain/OriginalQuantityValue.cs
src/MoBi.Core/Services/NameCorrector.cs
src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForSimulation.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTask.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForSimulation.cs
src/MoBi.Presentation/UICommand/CloneSimulationUICommand.cs
tests/MoBi.Tests/Core/MoBiSimulationSpecs.cs
tests/MoBi.Tests/Presentation/InteractionTasksForSimulationSpecs.cs

Fixes #521
Straight forward clone of a simulation.

Fixes #521 Clone simulation

---

appveyor-coverage.yml
appveyor-nightly.yml

Fixes #1266 Code coverage does not work anymore

---

appveyor-nightly.yml
appveyor.yml
src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

This just updates core version for hotfix 11.3
Unsure about the nightly build trigger since it does not seem to have a way to trigger from a specific branch in Appveyor-nightly.yml

Hotfix 11.3 core update

---

src/MoBi.Assets/AppConstants.cs

Fixes #1289 
just a typo fix
- [] No tests required

Fixes #1289 Organ export dialog - typo

---

src/MoBi.Presentation/Presenter/ParameterValuesPresenter.cs
src/MoBi.Presentation/Views/IPathAndValueEntitiesView.cs
src/MoBi.UI/Views/BasePathAndValueEntityView.cs

Fixes #1313 
Some extra whitespace in the ParameterValues view needs to be hidden

Fixes #1313 Parameter values UI

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

update core to 291

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForModule.cs
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/IntegrationTests/InteractionTasksForModuleSpecs.cs
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

1376 cannot load a spatial structures or a reactions bb

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Core/Domain/ClipboardData.cs
src/MoBi.Core/Services/ClipboardManager.cs
src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForFormulaFactory.cs
src/MoBi.Presentation/Presenter/FormulaCachePresenter.cs
src/MoBi.UI/Views/FormulaCacheView.cs
tests/MoBi.Tests/Core/FormulaCachePresenterSpecs.cs

Fixes #1314
While it's already possible to clone within a formula cache, copying and pasting between caches is implemented here.
Without formula already in the clipboard
With formula already in the clipboard
With formula in the clipboard, clicking in empty space

Fixes #1314 copy paste formulas

---

Tests/MoBi.Tests/Core/Commands/MoveBuildingBlockToModuleCommandSpecs.cs
src/MoBi.Assets/AppConstants.cs
src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/Commands/AddBuildingBlockToModuleCommand.cs
src/MoBi.Core/Commands/CopyBuildingBlockToModuleCommand.cs
src/MoBi.Core/Commands/MoveBuildingBlockToModuleCommand.cs
src/MoBi.Core/Commands/RemoveBuildingBlockFromModuleCommand.cs
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/Presenter/EditIndividualAndExpressionConfigurationsPresenter.cs
src/MoBi.Presentation/Presenter/EditModuleConfigurationsPresenter.cs
src/MoBi.Presentation/Presenter/Main/ExplorerPresenter.cs
src/MoBi.Presentation/Presenter/Main/ModuleExplorerPresenter.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForModule.cs
src/MoBi.UI/MoBi.UI.csproj
src/MoBi.UI/Views/ModuleExplorerView.Designer.cs
src/MoBi.UI/Views/ModuleExplorerView.cs
src/MoBi/MoBi.csproj
tests/MoBi.Tests/Core/Commands/CopyBuildingBlockToModuleCommandSpecs.cs
tests/MoBi.Tests/Core/Commands/MoveBuildingBlockToModuleCommandSpecs.cs
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.Tests/Presentation/EditIndividualAndExpressionConfigurationsPresenterSpecs.cs
tests/MoBi.Tests/Presentation/EditModuleConfigurationsPresenterSpecs.cs
tests/MoBi.Tests/Presentation/ModuleExplorerPresenterSpecs.cs
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #
Add copy and move functionality between nodes on node explorer

1358 move building blocks between modules

---

src/MoBi.Presentation/Presenter/AddBuildingBlocksToModulePresenter.cs
src/MoBi.Presentation/Views/IAddBuildingBlocksToModuleView.cs
src/MoBi.UI/Views/BaseModuleContentView.cs

Fixes #
Hide Default Merge Behavior Group when building blocks are added to module.

#1373 Hide Default Merge Behavior Group

---

src/MoBi.Assets/AppConstants.cs

Fixes #1365
Changed description over context menu

#1365 change menu name

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Core/Commands/AddContainerToSpatialStructureCommand.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTaskForParameter.cs
tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForParameterSpecs.cs

Fixes #1419

---

src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuFor.cs
src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForBuildingBlock.cs
src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForModule.cs
src/MoBi.Presentation/UICommand/RenameFromContextMenuCommand.cs

Fixes #1432 
Created a new Command for the Renaming actions executed from the treeview, both for Building Blocks and modules.

#1432 Rename from context menu

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/Domain/Extensions/ContainerExtensions.cs
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Core/Services/ForbiddenNamesRetriever.cs
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #1239 
removing the property type from ParameterBuildMode

1239 remove parameter type == property

---

src/MoBi.Presentation/Presenter/AddBuildingBlocksToModulePresenter.cs
src/MoBi.Presentation/Presenter/AddContentToModulePresenter.cs

Fixes #1437 
Fix a null referenced object when creating a new Initial Condition

#1437  fix possible null reference

---

src/MoBi.Core/Services/AdjustFormulaVisitor.cs
tests/MoBi.Tests/Core/AdjustFormulasVisitorSpecs.cs

Fixes #1454 
Prevent the open presenter from continually selecting/displaying the added formula as formulas are being added

Fixes #1454

---

src/MoBi.Presentation/Presenter/SelectNeighborPathPresenter.cs
tests/MoBi.Tests/Presentation/SelectNeighborPathPresenterSpecs.cs

Fixes #1430
disable selection dialog on not physical containters selected

#1430 disable selection dialog on not physical containters

---

src/MoBi.Presentation/Tasks/ObservedDataTask.cs
tests/MoBi.Tests/Presentation/Tasks/ObservedDataTasksSpecs.cs

Fixes #1491
This was fixed once for PK-Sim in https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2176. It appears that due to differences in how the data repositories are replaced, the error is duplicated in MoBi so has to be fixed separately.

Fixes #1491 Importer: "Reload under the same settings" does not work

---

src/Data/AllCalculationMethods.pkml

Fixes #1111 
Automatically generated pkml file replacement

Fixes #1111

---

src/MoBi.UI/Views/SelectBuildingBlockTypeView.Designer.cs

Fixes #1472 
Straight changes in designer code. I shrunk the view a bit as well to cut down on the empty space.

Fixes #1472 padding is off

---

src/MoBi.Presentation/Mappers/IndividualToParameterValuesMapper.cs
src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForParameterValuesFolder.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTaskFor.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForExpressionProfileBuildingBlock.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForIndividualBuildingBlock.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForPathAndValueEntity.cs
src/MoBi.Presentation/UICommand/AddIndividualAsParameterValuesCommand.cs
tests/MoBi.Tests/Presentation/Mapper/IndividualToParameterValuesMapperSpecs.cs

Fixes #1409
Load individual building blocks as Parameter Values.

#1409 load individual building blocks as Parameter Values

---

src/MoBi.Presentation/Presenter/SelectNeighborPathPresenter.cs
src/MoBi.Presentation/Presenter/SelectObjectInTreePresenter.cs
tests/MoBi.Tests/Presentation/SelectNeighborPathPresenterSpecs.cs

Fixes #1468
MAke sure we do not add the path manually when creating an absolute path

Fixes #1468

---

src/MoBi.Presentation/Presenter/BaseDiagram/MoBiBaseDiagramPresenter.cs
tests/MoBi.Tests/Presentation/MoBiBaseDiagramPresenterSpecs.cs

Fixes #1498 
When neighborhood is not present and selected diagram throws exception

#1498 Prevent null value from throwing error

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Core/Services/AdjustFormulaVisitor.cs
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/DTO/NeighborhoodBuilderDTO.cs
src/MoBi.Presentation/DTO/NeighborhoodDTO.cs
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/Core/AdjustFormulasVisitorSpecs.cs
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #1444
Comparing names of black box formulas
Updating core for new icons as well

Fixes #1444 wrong formula assigned

---

src/MoBi.Presentation/Presenter/SelectNeighborPathPresenter.cs
tests/MoBi.Tests/Presentation/SelectNeighborPathPresenterSpecs.cs

Fixes #1430
A couple of updates to cover the cases where a non-physical container is selected

Fixes #1430

---

src/MoBi.Presentation/Presenter/SelectContanerInTreePresenter.cs
src/MoBi.Presentation/Presenter/SelectOrganAndProteinsPresenter.cs
src/MoBi.Presentation/Tasks/Interaction/ParameterValuesTask.cs
src/MoBi.Presentation/Views/ISelectEntityInTreeView.cs
src/MoBi.UI/Views/SelectEntityInTreeView.cs
tests/MoBi.Tests/Presentation/SelectOrganAndProteinsPresenterSpecs.cs
tests/MoBi.Tests/Presentation/Tasks/ParameterValuesTaskSpecs.cs

Fixes #1456
Allows a user to select multiple containers where parameters will be added for the selected molecules

Fixes #1456 PV BB; "Add Protein expressioN" - multiselect of organs

---

src/MoBi.Presentation/Mappers/FormulaToValueFormulaDTOMapper.cs
tests/MoBi.Tests/Presentation/Tasks/FormulaToValueFormulaDTOMapperSpecs.cs

Fixes #1512
If there is a formula that is not Explicit - use the name as the placeholder to describe the formula

Fixes #1512 Distributed formulas are shown as <Not Available> in PV-like BBs

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Presentation/Presenter/CreateObjectPathsFromReferencesPresenter.cs
src/MoBi.Presentation/Presenter/ParameterValuesPresenter.cs
src/MoBi.Presentation/Tasks/Interaction/ParameterValuesTask.cs
src/MoBi.Presentation/Views/ICreateObjectPathsFromReferencesView.cs
src/MoBi.UI/Extensions/MemoEditExtensions.cs
src/MoBi.UI/Views/CreateObjectPathsFromReferencesView.Designer.cs
src/MoBi.UI/Views/CreateObjectPathsFromReferencesView.cs
src/MoBi.UI/Views/CreateObjectPathsFromReferencesView.resx
tests/MoBi.Tests/Presentation/CreateObjectPathsFromReferencesPresenterSpecs.cs
tests/MoBi.Tests/Presentation/ParameterValuesPresenterSpecs.cs
tests/MoBi.Tests/Presentation/Tasks/ParameterValuesTaskSpecs.cs

Fixes #1528 PV BB: New parameter value - add new entry by path
Fixes #1526 PV BB: New parameter value - required columns are not added
Adding the ability to bulk specify paths to add by hand so they don't have to be selected from the available valid paths. On the right is a text edit where users can add new lines by typing or copy/paste

Fixes #1528 PV BB: New parameter value - add new entry by path

---

src/MoBi.Presentation/Presenter/CreateModulePresenter.cs

Fixes #1518
Simple dto property change on construction

Fixes #1518 Make "Extend" the default merging behavior

---

src/MoBi.Core/NotificationMessage.cs
src/MoBi.UI/Views/NotificationView.cs

Fixes #1541 
The message column was not showing text. It was always empty

Fixes #1541 Notification text not showing in notification view

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Presentation/Presenter/ParameterValuesPresenter.cs

Fixes #1527
add warning for parameters value dimension

#1527 add warning for parameters value dimension

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/Commands/SetParentPathCommand.cs
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/Presenter/SpaceDiagram/SpacePopupMenus.cs
src/MoBi.UI/Diagram/DiagramManagers/SpatialStructureDiagramManager.cs
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #1497
pulling and using changes made in core.

Fixes #1497 no connections are shown for container parent path

---

src/MoBi.Core/Domain/UnitSystem/DimensionFactoryExtensions.cs
src/MoBi.Presentation/Presenter/EditFormulaPathListPresenter.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTaskForParameter.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForDistributedParameter.cs
tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForParameterSpecs.cs

Fixes #1274
Something might have become corrupted in the user settings, but we can cover that pretty easily

Fixes #1274 Error in adding a parameter

---

src/MoBi.Presentation/DTO/ValueFormulaDTO.cs
src/MoBi.Presentation/Presenter/PathAndValueBuildingBlockPresenter.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForPathAndValueEntity.cs

Fixes #1566
Allow selection of non-explicit formulas in the combobox

PV BB - Table formulas cannot be assigned #1566

---

src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForSimulation.cs

Fixes #1477 Always show the "Update from building block" action

---

src/MoBi.Presentation/Presenter/EditFormulaInContainerPresenter.cs
src/MoBi.Presentation/Presenter/EditFormulaInPathAndValuesPresenter.cs
src/MoBi.Presentation/Presenter/EditFormulaPresenter.cs
src/MoBi.Presentation/Tasks/Interaction/InitialConditionsTask.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForExtendablePathAndValueEntity.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForPathAndValueEntity.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForProjectPathAndValueEntityBuildingBlocks.cs
src/MoBi.UI/Views/CreateFormulaView.cs
src/MoBi.UI/Views/EditFormulaView.cs
tests/MoBi.Tests/Presentation/EditFormulaInContainerPresenterSpecs.cs
tests/MoBi.Tests/Presentation/EditFormulaInPathAndValuesPresenterSpecs.cs

Fixes #1586
There was an issue finding the correct Parameter value from the clone, and in the process a few usability issues were addressed

Fixes #1586 PV BB: assignment of new table formula - strange behavior

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/Presenter/EditFormulaInPathAndValuesPresenter.cs
src/MoBi.Presentation/Presenter/HierarchicalSpatialStructurePresenter.cs
src/MoBi.Presentation/Presenter/SpaceDiagram/SpatialStructureDiagramPresenter.cs
src/MoBi.Presentation/Tasks/Interaction/InitialConditionsTask.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForExtendablePathAndValueEntity.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForNeighborhood.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForPathAndValueEntity.cs
src/MoBi.UI/Diagram/DiagramManagers/SpatialStructureDiagramManager.cs
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

1561 exception when creating a neighborhood

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/Domain/Model/MoBiContext.cs
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForParameterValuesBuildingBlock.cs
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/Core/MoBiContextSpecs.cs
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #1597
Too many prompts for macro commands

Fixes  #1597 Macro commands prompt too many times

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Presentation/Tasks/SimulationCommitTask.cs
src/MoBi.Presentation/UICommand/CommitSimulationUICommand.cs
tests/MoBi.Tests/Presentation/Tasks/SimulationCommitTaskSpecs.cs

Fixes #1578
Add message with confirmation and information when commiting to BB From simulation
If last module has building blocks selected
if no building blocks are selected

1578 commit to bb

---

src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForParameterValuesBuildingBlock.cs
src/MoBi.Presentation/UICommand/ExtendBuildingBlockFromPathAndValuesUICommand.cs
src/MoBi.Presentation/UICommand/ExtendInitialConditionsFromInitialConditionsUICommand.cs
src/MoBi.Presentation/UICommand/ExtendParameterValuesFromPathAndValuesUICommand.cs

Fixes #1415
Adding one more import to PVBB from PKML

Fixes #1415 Extend PV and IC BB from PKML

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Presentation/MenusAndBars/ButtonGroupIds.cs
src/MoBi.Presentation/Presenter/Main/MenuAndToolBarPresenter.cs
src/MoBi.Presentation/Repositories/ButtonGroupRepository.cs

Fixes #1581
Caption change only. I renamed some internal stuff to be consistent.

Fixes #1581 Rename tab group "Edit Organism"

---

src/MoBi.Presentation/Presenter/Main/ModuleExplorerPresenter.cs
tests/MoBi.Tests/Presentation/ModuleExplorerPresenterSpecs.cs

Fixes #1634
When you remove the last IC or PV the folder node should be removed as well.

Fixes #1634 Possibility to delete initial conditions container missing

---

src/MoBi.Core/Mappers/PathAndValueEntityToDistributedParameterMapper.cs
src/MoBi.Presentation/DTO/PathAndValueEntityDTO.cs
src/MoBi.Presentation/Mappers/ExpressionProfileBuildingBlockToExpressionProfileBuildingBlockDTOMapper.cs
src/MoBi.Presentation/Mappers/IndividualBuildingBlockToIndividualBuildingBlockDTOMapper.cs
src/MoBi.Presentation/Mappers/InitialConditionsBuildingBlockToInitialConditionsBuildingBlockDTOMapper.cs
src/MoBi.Presentation/Mappers/ParameterValuesBuildingBlockToParameterValuesBuildingBlockDTOMapper.cs
src/MoBi.Presentation/Mappers/PathAndValueEntityBuildingBlockToPathAndValueEntityBuildingBlockDTOMapper.cs
src/MoBi.Presentation/Tasks/Interaction/InitialConditionsTask.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForExtendablePathAndValueEntity.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForPathAndValueEntity.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForProjectPathAndValueEntityBuildingBlocks.cs
src/MoBi.Presentation/Tasks/Interaction/ParameterValuesTask.cs
tests/MoBi.Tests/Core/Mapper/PathAndValueEntityToDistributedParameterMapperSpecs.cs
tests/MoBi.Tests/Presentation/ExpressionProfileBuildingBlockPresenterSpecs.cs
tests/MoBi.Tests/Presentation/IndividualBuildingBlockPresenterSpecs.cs
tests/MoBi.Tests/Presentation/InitialConditionsPresenterSpecs.cs
tests/MoBi.Tests/Presentation/Mapper/ExpressionProfileBuildingBlockToExpressionProfileBuildingBlockDTOMapperSpecs.cs
tests/MoBi.Tests/Presentation/Mapper/IndividualBuildingBlockToIndividualBuildingBlockDTOMapperSpecs.cs
tests/MoBi.Tests/Presentation/Mapper/InitialConditionsBuildingBlockToInitialConditionsBuildingBlockDTOMapperSpecs.cs
tests/MoBi.Tests/Presentation/Mapper/ParameterValuesBuildingBlockToParameterValuesBuildingBlockDTOMapperSpecs.cs
tests/MoBi.Tests/Presentation/ParameterValuesPresenterSpecs.cs
tests/MoBi.Tests/Presentation/PathAndValueEntityDTOSpecs.cs
tests/MoBi.Tests/Presentation/Tasks/InitialConditionsTaskSpecs.cs
tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForIndividualBuildingBlockSpecs.cs
tests/MoBi.Tests/Presentation/Tasks/ParameterValuesTaskSpecs.cs

Fixes #1665 
calculate a distribution value if the entity is distributed rather than show mean

Fixes #1665 Individual: mean value instead of value is shown for distributed parameters

---

src/MoBi.Core/Commands/EditObjectPropertyInBuildingBlockCommand.cs
src/MoBi.Core/Events/ObjectPropertyChangedEvent.cs
src/MoBi.Core/Helper/FormulaDecoder.cs
src/MoBi.Presentation/Presenter/EditFormulaPresenter.cs
tests/MoBi.Tests/Presentation/EditFormulaInPathAndValuesPresenterSpecs.cs

Fixes #1648
Error when Updating a simulation from BBs after a rollback of a formula value.

1648 Error when updating simulation from BB

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Presentation/Presenter/CreateObjectPathsFromReferencesPresenter.cs
src/MoBi.Presentation/Presenter/SelectSinglePresenter.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForExtendablePathAndValueEntity.cs
src/MoBi.Presentation/Tasks/Interaction/ParameterValuesTask.cs
src/MoBi.Presentation/Views/ICreateObjectPathsFromReferencesView.cs
src/MoBi.Presentation/Views/ISelectSingleView.cs
src/MoBi.UI/UIConstants.cs
src/MoBi.UI/Views/CreateObjectPathsFromReferencesView.cs
src/MoBi.UI/Views/SelectSingleView.cs

Fixes #1646
We had defined the window sizes without accounting for font scaling

Fixes #1646 Window too small

---

src/MoBi.Presentation/Presenter/Main/ModuleExplorerPresenter.cs
tests/MoBi.Tests/Presentation/ModuleExplorerPresenterSpecs.cs

Fixes #1632
Missing an event handler

Fixes #1632 new molecule not visible in module

---

src/MoBi.Presentation/Presenter/SelectReferenceAtParameterValuePresenter.cs
src/MoBi.Presentation/Presenter/SelectReferencePresenterBase.cs
tests/MoBi.Tests/Presentation/SelectReferenceAtParameterValuePresenterSpecs.cs

Fixes #1631
Adding parameter values for "MoleculeProperties" does not work as expected

#1631 PV BB adding parameter values does not work as expected

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Core/Commands/ClearOriginalQuantitiesTrackerCommand.cs
src/MoBi.Presentation/Presenter/SimulationChangesPresenter.cs
tests/MoBi.Tests/Core/Commands/ClearOriginalQuantitiesTrackerCommandSpecs.cs

Fixes #1657
Simple serialize/deserialize to allow the command to be reversible.

Fixes #1657 commit to building blocks rollback

---

src/MoBi.Presentation/Presenter/SelectReferenceAtParameterValuePresenter.cs
tests/MoBi.Tests/Presentation/SelectReferenceAtParameterValuePresenterSpecs.cs

Fixes #1696
V add Parameter Value not working as expected

#1696 PV add Parameter Value not working as expected

---

src/MoBi.Assets/AppConstants.cs

Fixes #1578
Changes on message when commiting to Building Blocks

1578 commit to bb fixes

---

src/MoBi.Presentation/Presenter/SelectReferenceAtParameterValuePresenter.cs
tests/MoBi.Tests/Presentation/SelectReferenceAtParameterValuePresenterSpecs.cs

Fixes #1622
Allow relative path selection

Fixes #1622 "Edit formula" in PV BB should support "Relative path"

---

src/MoBi.UI/Diagram/DiagramManagers/SpatialStructureDiagramManager.cs

Fixes #1722
The diagram should be shown

Fixes #1722 Diagram of a spatial structure not shown

---

src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForInitialConditionsBuildingBlock.cs

#1720 Import from excel rename menu

---

src/MoBi.UI/Views/CreateSimulationConfigurationView.Designer.cs

Fixes #1734
Designer change only

Fixes #1734 Put the check under the name?

---

src/MoBi.Presentation/Presenter/SelectReferenceAtParameterValuePresenter.cs
src/MoBi.Presentation/Presenter/SelectReferencePresenterBase.cs
tests/MoBi.Tests/Presentation/SelectReferenceAtParameterValuePresenterSpecs.cs

Fixes #1715 
Select parameter window shows no parameters from the own module

#1715 Select parameter window shows no parameters from the own module

---

src/MoBi.Core/Serialization/ORM/Mappers/ProjectMetaDataToProjectMapper.cs
tests/MoBi.Tests/Core/ProjectMetaDataToProjectMapperSpecs.cs

Fixes #1750
Test to rebuilt Simulation does not Work in Mobi12beta

#1720 Test to rebuilt Simulation does not Work in Mobi12beta

---

src/MoBi.Presentation/Presenter/SelectReferenceAtParameterValuePresenter.cs
tests/MoBi.Tests/Presentation/SelectReferenceAtParameterValuePresenterSpecs.cs

Fixes #1757 Add new PV: sub-containers of an Individual are not sorted alphabetically

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.UI/Views/BaseModuleContentView.cs

Fixes #1361
Just adding a clickable link in the label

#1361 new module default merge behavior add link to documentation

---

src/MoBi.UI/Views/IndividualBuildingBlockView.cs

Fixes #1751
Initially we had this disabled, but seems that we should not disable it.

Fixes #1751 Show Column Chooser in the individual view

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.UI/Views/CreateObjectPathsFromReferencesView.Designer.cs
src/MoBi.UI/Views/CreateObjectPathsFromReferencesView.cs

Fixes #1752
I didn't explicitly say copy/paste, but it's clear you can edit, add

Fixes #1752 Explanation label for adding new parameter values per copy/paste

---

src/MoBi.Core/Commands/SetCreateProcessRateParameterCommand.cs
src/MoBi.UI/Diagram/DiagramManagers/SpatialStructureDiagramManager.cs
tests/MoBi.Tests/Core/Commands/SetCreateProcessRateParameterCommandSpecs.cs

Fixes #1561 Exception when creating a neighborhood

---

src/MoBi.Presentation/DTO/EventAssignmentBuilderDTO.cs
tests/MoBi.Tests/Presentation/EventAssignmentBuilderDTOSpecs.cs

Fixes #1785 Event assignments not working when target is not within builder

---

src/MoBi.UI/Services/MoBiApplication.cs

Fixes #341
Ctrl-F4 is the MDI version of this shortcut. This implements the Ctrl-W implementation. The way it's done here it won't matter if the view being closed is the active view or if the user has selected a module or simulation in the explorer views. This seems to match how Ctrl-f4 works. It does not matter what is active in the view, it's the active MDI view that is closed.
I'll do the same for PK-Sim when this is merged.

Add ctrlw for close tab

---

src/MoBi.Presentation/Tasks/ObservedDataTask.cs
src/MoBi.Presentation/UICommand/ReloadAllObservedDataCommand.cs
tests/MoBi.Tests/Presentation/Tasks/ObservedDataTasksSpecs.cs

Fixes #1491 
When using the funtion to "Reload under the same settings", and the updated data set has less values that the previous one and it was used in a PI

2179 pending changes still when merging ospsuitcore

---

.github/workflows/build-and-test.yml
.github/workflows/build-nightly.yml
rakefile.rb
src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForContainer.cs
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.UI/AboutView.resx
src/MoBi.UI/MoBi.UI.csproj
src/MoBi.UI/Views/SplashScreen.resx
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.Tests/Presentation/DataRepositoryComparer.cs
tests/MoBi.Tests/Presentation/EditIndividualAndExpressionConfigurationsPresenterSpecs.cs
tests/MoBi.Tests/Presentation/EditReactionBuildingBlockPresenterSpecs.cs
tests/MoBi.Tests/Presentation/EditSimulationPresenterSpecs.cs
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #1813 
Updating core and all 3rd party dependencies

Fixes #1813 Update dependencies

---

src/MoBi.Presentation/Presenter/MoBiMainViewPresenter.cs

Profile and address various slow performance

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Presentation/DTO/ParameterDTO.cs
src/MoBi.Presentation/Mappers/IndividualParameterToParameterDTOMapper.cs
src/MoBi.Presentation/Mappers/ParameterToParameterDTOMapper.cs
src/MoBi.Presentation/Mappers/PathWithValueToDTOMapper.cs
src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForObservedDataFolder.cs
src/MoBi.Presentation/Presenter/BasePresenter/AbstractContainerEditPresenterWithParameters.cs
src/MoBi.Presentation/Presenter/EditContainerPresenter.cs
src/MoBi.Presentation/Presenter/EditParameterListPresenter.cs
src/MoBi.Presentation/Presenter/EditParametersInContainerPresenter.cs
src/MoBi.Presentation/Presenter/EditSpatialStructurePresenter.cs
src/MoBi.Presentation/Views/IEditParametersInContainerView.cs
src/MoBi.UI/Views/EditParametersInContainerView.Designer.cs
src/MoBi.UI/Views/EditParametersInContainerView.cs
tests/MoBi.Tests/Core/Mapper/ParameterToDTOParameterMapperSpecs.cs
tests/MoBi.Tests/Presentation/EditContainerPresenterSpecs.cs
tests/MoBi.Tests/Presentation/EditParametersInContainerPresenterSpecs.cs
tests/MoBi.Tests/Presentation/Mapper/IndividualParameterToParameterDTOMapperSpecs.cs
tests/MoBi.Tests/Presentation/Mapper/When_mapping_from_individual_to_dto_for_simple_parameter_with_value.cs

Creating a hybrid preview where an individual can be selected and the parameter list of the spatial structure will show relevant parameters from the individual.
Upcoming for part 2 will be editing the individual parameters while in preview of spatial structure.
Making this grid read-only for the IndividualParameters made this a lot simpler.

Task 1 of 2 - Spatial Structure w/ Individual selection for preview #947

---

src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForContainer.cs
src/MoBi.Presentation/Presenter/EditParametersInContainerPresenter.cs
src/MoBi.Presentation/Presenter/HierarchicalSimulationPresenter.cs
tests/MoBi.Tests/Presentation/EditParametersInContainerPresenterSpecs.cs
tests/MoBi.Tests/Presentation/HierarchicalSimulationPresenterSpecs.cs

Fixes #1831
We just use a different method in the resolver task for this.

Fixes #1831 Copy path for an entity from simulation - do not include simulation name

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Assets/ToolTips.cs
src/MoBi.Presentation/Presenter/EditIndividualParameterPresenter.cs
src/MoBi.Presentation/Presenter/EditParametersInContainerPresenter.cs
src/MoBi.Presentation/Views/IEditIndividualParameterView.cs
src/MoBi.UI/Views/EditIndividualParameterView.Designer.cs
src/MoBi.UI/Views/EditIndividualParameterView.cs
src/MoBi.UI/Views/EditParametersInContainerView.cs
tests/MoBi.Tests/Presentation/EditIndividualParameterPresenterSpecs.cs

Fixes #1843
selection with tooltip
This is the view. You can only see the name and the instruction with the navigate button

1843 show individual in spatial structure

---

src/MoBi.Presentation/Mappers/ParameterToParameterDTOMapper.cs

Fixes #1854 
IoC registration bug that was introduced in a previous commit in 12.1

Fixes #1854 Cannot start sensitivity analysis from Simulation

---

src/MoBi.Presentation/Presenter/EditFavoritesPresenterInSimulation.cs
src/MoBi.Presentation/Presenter/EditParameterListPresenterExtensions.cs
tests/MoBi.Tests/Presentation/EditFavoritesInSimulationPresenterSpecs.cs

Fixes #160 Favorites list: Column "Simulation" is expendable

---

src/MoBi.Core/Helper/FormulaTypeCaptionRepository.cs
src/MoBi.Presentation/Presenter/EditFormulaPresenter.cs
src/MoBi.UI/Views/CreateFormulaView.cs
src/MoBi.UI/Views/EditFormulaView.Designer.cs
src/MoBi.UI/Views/EditFormulaView.cs
src/MoBi.UI/Views/EditFormulaView.resx
tests/MoBi.Tests/Presentation/EditFormulaInContainerPresenterSpecs.cs

Fixes #1844
Distributed Table Formula is not supported as a 'creatable' type in MoBi. This allows the user to see the type but not allow user to create this type of formula
Type combobox is hidden and a text edit is shown instead

Fixes #1844 Individual BB: "Formula type" not shown for table formulas?

---

src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/Commands/UpdateSimulationCommand.cs
src/MoBi.Core/Domain/Model/MoBiSimulation.cs
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.Presentation/Tasks/SimulationUpdateTask.cs
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/Core/Commands/UpdateSimulationCommandSpecs.cs
tests/MoBi.Tests/Core/MoBiSimulationSpecs.cs
tests/MoBi.Tests/Core/Service/SimulationUpdateTaskSpecs.cs
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #1864
Make sure we actually use the SimulationReference also when configuring a simulation

Fixes #1864

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.UI/Views/DistributedPathAndValueEntityView.cs

Fixes #1867
Button wording change

Fixes #1867 Add warning when converting distributed formula to constant

---

src/MoBi.Presentation/Tasks/SpatialStructureContentExporter.cs
tests/MoBi.Tests/Presentation/Tasks/SpatialStructureContentExporterSpecs.cs

Fixes #1866
Name the temporary spatial structure when exporting

Fixes #1866 Export spatial structure and individual import only spatial structure, no name

---

src/MoBi.UI/Views/EditParametersInContainerView.cs

Fixes #1878
Swaps the visible index if they are in the wrong order

Fixes #1878 Order of the columns Building Block and Module in a simulation seems random

---

src/MoBi.Core/Helper/FormulaDecoder.cs
tests/MoBi.Tests/Presentation/Tasks/SimulationRunnerSpecs.cs

Fixes #1884
Warnings Removal from code

#1884 remove warnings

---

src/MoBi.Core/Commands/RenameObjectBaseCommand.cs
tests/MoBi.Tests/Core/Commands/RenameObjectBaseCommandSpecs.cs

Fixes #1892
Freshly broken by me yesterday

Fixes #1892 Rename simulation does not rename the simulation

---

rakefile.rb
src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Core/ProjectVersions.cs
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #1902
increments the version number

1902 bump version number

---

src/MoBi.Presentation/Presenter/HierarchicalSimulationPresenter.cs

Fixes #1639
There was a check for if the simulation had any favorites for some reason. If no favorites, no context menu

Fixes #1639 Copy path of a parameter/container in the simulation

---

src/MoBi.Core/Snapshots/Mappers/SimulationMapper.cs
tests/MoBi.Tests/IntegrationTests/Snapshots/ProjectLoadSpecs.cs

Fixes #1935
Run simulations when importing

Run Simulations when importing snapshots

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Assets/MoBi.Assets.csproj
src/MoBi.BatchTool/MoBi.BatchTool.csproj
src/MoBi.CLI.Core/CLIRegister.cs
src/MoBi.CLI.Core/MoBi.CLI.Core.csproj
src/MoBi.CLI.Core/Services/QualificationRunner.cs
src/MoBi.CLI/MoBi.CLI.csproj
src/MoBi.CLI/Program.cs
src/MoBi.CLI/Properties/launchSettings.json
src/MoBi.CLI/QualificationRunCommand.cs
src/MoBi.Core/MoBi.Core.csproj
src/MoBi.Core/Snapshots/Project.cs
src/MoBi.Engine/MoBi.Engine.csproj
src/MoBi.Presentation/MoBi.Presentation.csproj
src/MoBi.R/MoBi.R.csproj
src/MoBi.UI/MoBi.UI.csproj
src/MoBi/MoBi.csproj
tests/MoBi.HelpersForTests/MoBi.HelpersForTests.csproj
tests/MoBi.Tests/MoBi.Tests.csproj
tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj

Fixes #1965
Create the basic QualificationRunner with each step to be filled in one-by-one for MoBi.

1965 create a qualification batch run command

---

src/MoBi.UI/Views/EditParametersInContainerView.cs

Fixes #1980
remove from column chooser

Fixes #1980 Delete parameter can be selected per column chooser

---

src/MoBi.Core/Domain/Model/MoBiProject.cs
tests/MoBi.Tests/IntegrationTests/SearchIntegrationTests.cs

Fixes #1993
Search did not find any results for module building blocks

Fixes #1993 Search not working for building blocks

---

src/MoBi.CLI.Core/Services/ProjectTask.cs
tests/MoBi.R.Tests/Services/ProjectTaskSpecs.cs

Fixes #2015 
Fixes #2014 
When a file does not exist, or cannot be read, an exception should result.

Fixes #2015

---

src/MoBi.Presentation/Presenter/Main/ModuleExplorerPresenter.cs
src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForModule.cs
tests/MoBi.Tests/IntegrationTests/InteractionTasksForModuleSpecs.cs
tests/MoBi.Tests/Presentation/ModuleExplorerPresenterSpecs.cs

(cherry picked from commit 3975b9f9672a0198887af0bacd3bf17913d63b69)
Fixes #2050
Just didn't quite push this last change in time

pr feedback

---

src/MoBi.Assets/AppConstants.cs
src/MoBi.Presentation/DTO/NeighborhoodBuilderDTO.cs
src/MoBi.Presentation/DTO/NeighborhoodObjectPathDTO.cs
src/MoBi.Presentation/Presenter/SelectNeighborPathPresenter.cs

Fixes #2062
Prevent neighborhood creation from at least one logical container

2062 do not create neighborhoods between logical containers

---

src/MoBi.UI/Views/EditMoleculeBuilderView.cs

Fixes #2065
Missing an exception handler for an event

Fixes #2065 Exception when trying to change molecule type to "stationary"

---

src/MoBi.Presentation/Presenter/BuildingBlockWithInitialConditionsPresenter.cs
tests/MoBi.Tests/Presentation/InitialConditionsPresenterSpecs.cs

Fixes #2091
Bool was not passed on to methods

Fixes #2091 "Negative values allowed" check box behavior
