Open-Systems-Pharmacology/MoBi

src/MoBi.Engine/Sbml/MoleculeInformation.cs, tests/MoBi.Tests/Core/SBML/MoleculeInformationSpecs.cs
Fixes #610 (only shows duplicated in compartment warning when there is in fact a problem)
=> only shows duplicated in compartment warning when there is in fact a problem

src/MoBi.Engine/Sbml/AssignmentImporterBase.cs, tests/MoBi.Tests/Core/SBML/AssignmentImporterSpecs.cs, tests/MoBi.Tests/Core/SBML/ContextForSBMLIntegration.cs, tests/MoBi.Tests/Core/SBML/SBMLTaskSpecs.cs, tests/MoBi.Tests/Core/SBML/Testfiles/tiny_example_12.xml, tests/MoBi.Tests/MoBi.Tests.csproj
Fixes #607  Assignment Importer should use absolute paths so it can be used so set values to other building blocks
=> Assignment Importer should use absolute paths so it can be used so set values to other building blocks

src/MoBi.Core/Domain/UnitSystem/MoBiDimensionFactory.cs, src/MoBi.Engine/Sbml/SpeciesImporter.cs, src/MoBi.Engine/Sbml/UnitDefinitionImporter.cs, tests/MoBi.Tests/Core/SBML/SpeciesImporterSpecs.cs
Fixes #616 (Litre are recognized as a unit when importing sbml files)
=> Litre are recognized

src/MoBi.Assets/AppConstants.cs, src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.Assets/ToolTips.cs, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/Domain/Model/MoBiProject.cs, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MenusAndBars/MenuBarItemIds.cs, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/PresentationRegister.cs, src/MoBi.Presentation/Presenter/Main/MenuAndToolBarPresenter.cs, src/MoBi.Presentation/Presenter/Main/ModuleExplorerPresenter.cs, src/MoBi.Presentation/RegionNames.cs, src/MoBi.Presentation/Repositories/ButtonGroupRepository.cs, src/MoBi.Presentation/Repositories/MenuBarItemRepository.cs, src/MoBi.Presentation/Tasks/ProjectTask.cs, src/MoBi.Presentation/UICommand/ShowModuleExplorerCommand.cs, src/MoBi.Presentation/Views/IModuleExplorerView.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi.UI/Views/MoBiMainView.Designer.cs, src/MoBi.UI/Views/MoBiMainView.cs, src/MoBi.UI/Views/MoBiMainView.resx, src/MoBi.UI/Views/ModuleExplorerView.Designer.cs, src/MoBi.UI/Views/ModuleExplorerView.cs, src/MoBi/MoBi.csproj, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/BuildingBlockExplorerPresenterSpecs.cs, tests/MoBi.Tests/Presentation/ModuleExplorerPresenterSpecs.cs, tests/MoBi.Tests/Presentation/ProjectTaskSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
I implemented this default module feature similar to how new building blocks are added to blank projects. In this screenshot I was adding 2 PSV and 1 MSV just to get the folder logic correct.
We get the context menus, but some entries will have to be changed around. I'm going to take that task on next with #823 .
=> Fixes #816 View and Presenter for the Module Explorer

src/MoBi.Assets/AppConstants.cs, src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.Assets/ToolTips.cs, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuFactoryForBuildBlocks.cs, src/MoBi.Presentation/MenusAndBars/MenuBarItemIds.cs, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Nodes/RootNodeType.cs, src/MoBi.Presentation/Presenter/Main/MenuAndToolBarPresenter.cs, src/MoBi.Presentation/Presenter/Main/ModuleExplorerPresenter.cs, src/MoBi.Presentation/Repositories/ButtonGroupRepository.cs, src/MoBi.Presentation/Repositories/MenuBarItemRepository.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi/MoBi.csproj, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/ModuleExplorerPresenterSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Removing the references to 'Extension' from some spots in the UI.
Module Explorer gets one folder instead of two
New ribbon buttons just get a text change.
=> Fixes #981 Remove distinction of Extension vs. PK-Sim modules

src/MoBi.UI/Views/CreateSimulationConfigurationView.Designer.cs, src/MoBi.UI/Views/EditIndividualAndExpressionConfigurationsView.Designer.cs, src/MoBi.UI/Views/EditModuleConfigurationsView.Designer.cs
Somewhere along the line the auto-select individual was already fixed.
This is just designer changes to make the default view size look more symmetrical
=> Fixes #962 Create Simulation Layout and workflow

src/MoBi.Core/Serialization/ORM/Mappers/ProjectMetaDataToProjectMapper.cs, tests/MoBi.Tests/Core/ProjectMetaDataToProjectMapperSpecs.cs
The mapper created a blank module every time a project was opened, even if no building blocks needed a home.
=> Fixes #1030 Blank module created for all saved projects

src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/DTO/AddBuildingBlocksToModuleDTO.cs, src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForInitialConditionsFolder.cs, src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForModuleBuildingBlockCollection.cs, src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForParameterValuesFolder.cs, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Nodes/InitialConditionsFolderNode.cs, src/MoBi.Presentation/Nodes/TreeNodeFactory.cs, src/MoBi.Presentation/Presenter/AddBuildingBlocksToModulePresenter.cs, src/MoBi.Presentation/Presenter/Main/ExplorerPresenter.cs, src/MoBi.Presentation/Presenter/Main/ModuleExplorerPresenter.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForModule.cs, src/MoBi.Presentation/UICommand/AddNewInitialConditionsBuildingBlockUICommand.cs, src/MoBi.Presentation/UICommand/AddNewParameterValuesBuildingBlockUICommand.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi.UI/Views/AddBuildingBlocksToModuleView.cs, src/MoBi.UI/Views/BaseModuleContentView.Designer.cs, src/MoBi.UI/Views/BaseModuleContentView.cs, src/MoBi/MoBi.csproj, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/ModuleExplorerPresenterSpecs.cs, tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForModuleSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Re-using the standard "AddBuildingBlocks" dialog to add either Parameter Values or Initial Conditions building blocks when a user right clicks on the folder node.
Also, double click expands/contracts the folder node similar to other collector/folder nodes
=> Add context menu "new building block" to IC and PV BBs #1015

src/MoBi.Presentation/Presenter/EditIndividualAndExpressionConfigurationsPresenter.cs
When configured an existing simulation, the node for the selected expression appeared in the unselected expression pane.
This was just an order of operations problem.
=> Fixes #1051 Expression doubled when configuring a simulation

src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/Domain/Extensions/BuildingBlockExtensions.cs, src/MoBi.Core/Domain/Model/MoBiSimulation.cs, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Core/Services/SimulationConfigurationFactory.cs, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Nodes/BuildingBlockNode.cs, src/MoBi.Presentation/Nodes/TreeNodeFactory.cs, src/MoBi.Presentation/Presenter/Main/SimulationExplorerPresenter.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForSimulation.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi/MoBi.csproj, tests/MoBi.Tests/Core/Service/RenameInSimulationTaskSpecs.cs, tests/MoBi.Tests/Core/Service/SimulationConfigurationFactorySpecs.cs, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/InteractionTasksForSimulationSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
This is just the start of working on update/commit.
For this first step, I just want to get the green/red checks working when the user updates the template building block.
In that case it's just a simple check of BuildingBlock version.
But you do not have the direct link between simulation building blocks and template building blocks that you had in version 11. Instead, we have to find the matching template based on parent module, building block name and type. Once found, the versions can be compared.
=> Fixes #1052 Update/Commit - sync red/green checks with building block versions

src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/Commands/AddBuildingBlockToModuleCommand.cs, src/MoBi.Core/Commands/ModuleContentChangedCommand.cs, src/MoBi.Core/Commands/RemoveBuildingBlockFromModuleCommand.cs, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Core/Services/TemplateResolverTask.cs, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/DTO/ModuleConfigurationDTO.cs, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Nodes/ModuleConfigurationNode.cs, src/MoBi.Presentation/Presenter/Main/SimulationExplorerPresenter.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForSimulation.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi/MoBi.csproj, tests/MoBi.Tests/Core/Commands/AddBuildingBlockToModuleCommandSpecs.cs, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/InteractionTasksForSimulationSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
If you add a building block to a module simulations using that module should be marked as out of sync.
Special attention for initial conditions and parameter values, because the module can have multiple instances, but only one can be in use in a simulation so adding those does not change the sync status.
Remove is similar, except it is also not possible to remove a building block from a module if the building block is in use. Again, only IC's and PV's can be removed from a module that's in use, and only if they are not selected.
=> 1067 simulation status when a module is updated

src/MoBi.Assets/AppConstants.cs, src/MoBi.Core/Commands/ClearOriginalQuantitiesTrackerCommand.cs, src/MoBi.Core/Commands/SynchronizeInitialConditionCommand.cs, src/MoBi.Core/Commands/SynchronizeParameterValueCommand.cs, src/MoBi.Presentation/Tasks/SimulationCommitTask.cs
Non reversible command added at the end.
I verified that if I put this command in first, the whole macro is non-reversible. It doesn't matter.
=> Fixes #1090 SynchronizeParameterValueCommand does not undo the changes

src/MoBi.Presentation/Presenter/PathAndValueBuildingBlockPresenter.cs
Little oopsie from a previous bug fix.
=> Fixes #1127 Warning SetValueOrigin hides method from base class

.github/PULL_REQUEST_TEMPLATE.md, src/MoBi.Assets/AppConstants.cs, src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/DTO/IndividualAndFilePathDTO.cs, src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuFor.cs, src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForContainer.cs, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Presenter/SelectFolderAndIndividualFromProjectPresenter.cs, src/MoBi.Presentation/Tasks/Edit/EditTaskForContainer.cs, src/MoBi.Presentation/UICommand/SaveWithIndividualUICommand.cs, src/MoBi.Presentation/Views/ISelectFolderAndIndividualFromProjectView.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi.UI/Views/SelectFolderAndIndividualFromProjectView.Designer.cs, src/MoBi.UI/Views/SelectFolderAndIndividualFromProjectView.cs, src/MoBi.UI/Views/SelectFolderAndIndividualFromProjectView.resx, src/MoBi.UI/Views/SelectSpatialStructureAndMoleculesView.Designer.cs, src/MoBi.UI/Views/UserSettingsView.cs, src/MoBi/MoBi.csproj, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/CreateSimulationConfigurationPresenterSpecs.cs, tests/MoBi.Tests/Presentation/IndividualAndFilePathDTOSpecs.cs, tests/MoBi.Tests/Presentation/SelectFolderAndIndividualFromProjectPresenter.cs, tests/MoBi.Tests/Presentation/SelectFolderAndIndividualFromProjectPresenterSpecs.cs, tests/MoBi.Tests/Presentation/Tasks/EditTaskForContainerSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
You open the context menu and select 'Export With Individual'.  Any suggestions for this context menu are appreciated
Can't close without specifying both individual and file path. The file path button opens the standard file browser.
Ok, saves the container PKML with additional parameters from the individual where they match the container path
=> Fixes #1143 select individual when exporting container from spatial structure

src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForContainerBase.cs, tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForContainerSpecs.cs
Nothing has changed in the UI for this feature.
- if a rename has happened to an imported container then the neighborhoods will be search by name and by FirstNeighborPath and SecondNeighborPath for the string matching the old container name.
- if found, the name, or matching path element will be replaced with the new name.
=> Fixes #1139 Import and rename container into spatial structure with neighborhood

.github/PULL_REQUEST_TEMPLATE.md, appveyor.yml, src/MoBi.Assets/AppConstants.cs, src/MoBi.Presentation/MenusAndBars/ContextMenus/RootContextMenuForModule.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTask.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTaskFor.cs, src/MoBi.Presentation/Tasks/ModuleLoader.cs, src/MoBi.Presentation/UICommand/LoadModuleUICommand.cs, src/MoBi.Presentation/UICommand/NewModuleWithBuildingBlocksUICommand.cs, tests/MoBi.Tests/Presentation/Tasks/ModuleLoaderSpecs.cs
Fixes #1133
If the user loads modules from a PKML file, this new feature checks if they are loading them directly from a SimulationTransfer. If so, the user is prompted to optionally load Individuals and Expressions from the SimulationTranfer.
Text and pluralization is different if there is only one building block, or if there is only building blocks for one of the types.
=> Fixes #1133 Prompt users to import more than just module

.github/PULL_REQUEST_TEMPLATE.md, src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/Commands/AddBuildingBlockToModuleCommand.cs, src/MoBi.Core/Commands/AddModuleCommand.cs, src/MoBi.Core/Commands/AddSimulationCommand.cs, src/MoBi.Core/Events/Events.cs, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Core/Services/BuildingBlockVersionUpdater.cs, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Nodes/ModuleConfigurationNode.cs, src/MoBi.Presentation/Nodes/TreeNodeFactory.cs, src/MoBi.Presentation/Presenter/Main/ModuleExplorerPresenter.cs, src/MoBi.Presentation/Presenter/Main/SimulationExplorerPresenter.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi/MoBi.csproj, tests/MoBi.Tests/Core/BuildingBlockVersionUpdaterSpecs.cs, tests/MoBi.Tests/Core/Commands/AddModuleCommandSpecs.cs, tests/MoBi.Tests/Core/Commands/AddSelectedBuildingBlockToLastModuleConfigurationCommandSpecs.cs, tests/MoBi.Tests/Core/Commands/RemoveSelectedBuildingBlockFromLastModuleConfigurationCommandSpecs.cs, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/InteractionTasksForSimulationSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Fixes #1141
We are adding the concept of PK-Sim modules back. They aren't readonly, but you get an indication if a module is as-it-was-exported from PK-Sim. Building block changes trigger a change in the icon.
https://github.com/Open-Systems-Pharmacology/docs/issues/227
=> Fixes #1141 Visual indication when a PK-Sim module has been changed

src/MoBi.Presentation/DTO/ExpressionParameterDTO.cs, src/MoBi.Presentation/DTO/IPathAndValueEntityDTO.cs, src/MoBi.Presentation/DTO/IndividualParameterDTO.cs, src/MoBi.Presentation/DTO/StartValueDTO.cs, src/MoBi.Presentation/Presenter/BuildingBlockWithInitialConditionsPresenter.cs, src/MoBi.Presentation/Presenter/ExpressionProfileInitialConditionsPresenter.cs, src/MoBi.Presentation/Presenter/PathWithValueBuildingBlockPresenter.cs, src/MoBi.Presentation/Views/IPathAndValueEntitiesView.cs, src/MoBi.UI/Views/BasePathAndValueEntityView.cs, src/MoBi.UI/Views/InitialConditionsView.cs
Fixes #1175 
When editing parameter values of an expression profile, you cannot change name or path elements of any of the entries. That should be the same for initial conditions
https://github.com/Open-Systems-Pharmacology/docs
https://github.com/Open-Systems-Pharmacology/developer-docs
=> Fixes #1175 Expression Profile: Initial conditions paths should not be editable

src/MoBi.Assets/AppConstants.cs, src/MoBi.Presentation/Tasks/Edit/EditTaskFor.cs, src/MoBi.Presentation/Tasks/Edit/EditTasksForTransporterMoleculeContainer.cs, src/MoBi.UI/Views/SelectRenamingView.cs, tests/MoBi.Tests/Presentation/Tasks/EditTaskForContainerSpecs.cs
Fixes #1154 
The original code would search for related entities to rename among all building blocks in a project. Now we want to limit the scope of renaming to the module.
There are a few extra cases to handle - the edit task is used to rename entities that do not belong in a module. For example, IndividualBuildingBlock, and simulation.
=> Fixes  #1154 Limit renaming related entites to module

src/MoBi.Presentation/Presenter/Main/ModuleExplorerPresenter.cs, tests/MoBi.Tests/Presentation/ModuleExplorerPresenterSpecs.cs
Fixes #1158
When adding modules, the module explorer should automatically expand the root node and the node of the added module.
If the module contains only one building block, then that building block should be opened for editing
=> Fixes #1158 Usability issue: adding a new module should expand it

src/MoBi.Assets/AppConstants.cs, src/MoBi.Presentation/Presenter/EditIndividualAndExpressionConfigurationsPresenter.cs, src/MoBi.UI/Views/EditIndividualAndExpressionConfigurationsView.cs, tests/MoBi.Tests/Presentation/EditIndividualAndExpressionConfigurationsPresenterSpecs.cs
Fixes #1190 Do not allow multiple expression profile for same protein
Fixes #1101 Simulation Configuration: enable multiselect
Fixes #
When configuring a simulation, it should not be possible for the user to select two expression profiles for the same protein. This is done by an error message dialog after the user selects add
Also, allow users to add/remove multiple expressions at once with the add and remove buttons
=> Fixes #1190 and Fixes #1101

src/MoBi.Core/Commands/RemoveModuleCommand.cs, tests/MoBi.Tests/Core/Commands/RemoveModulecommandSpecs.cs
Fixes #1201
If a module is removed from a project, any editors that are open for the modules building blocks should be closed.
=> Fixes #1201 Deleting a module with an open building block leaves editors open

src/MoBi.Assets/AppConstants.cs
Fixes #1157
Added the word "Events" to a list of words that are not allowed to be used for container names
=> FIxes #1157 "Events" should not be allowed as name for any container

src/MoBi.Core/Services/ForbiddenNamesRetriever.cs, tests/MoBi.Tests/Core/Service/ForbbidenNamesRetrieverSpecs.cs
Fixes #1207 
We no longer have to prevent simulation naming sharing a name with event.
=> Fixes #1207 Simulation should be able to share name with events

src/MoBi.Presentation/Presenter/BaseDiagram/MoBiBaseDiagramPresenter.cs, src/MoBi.Presentation/Presenter/HierarchicalStructurePresenter.cs, tests/MoBi.Tests/Presentation/HierarchicalStructurePresenterSpecs.cs
Fixes #1152
When first or second neighbor nodes are selected in a spatial structure, the diagram manager does not handle a case where the EntitySelectedEvent is built without an ObjectBase.
I chose not to publish the event in this case, but alternatively, we could handle the case where the event is handled without ObjectBase
=> Fixes #1152 crash when selecting a neighbor in a neighborhood after opening the diagram

src/MoBi.Assets/AppConstants.cs, src/MoBi.Presentation/Tasks/ModuleLoader.cs
Fixes #1188 
In the dialog box we just number the additional building blocks that would be imported, but we can name them for more clarity.
=> Fixes #1188 When importing SimulationTransfer as Module name the additional building blocks

src/MoBi.Presentation/DTO/ContainerDTO.cs, src/MoBi.Presentation/DTO/ModuleAndSpatialStructureDTO.cs, src/MoBi.Presentation/DTO/SpatialStructureDTO.cs, src/MoBi.Presentation/Mappers/ModuleToModuleAndSpatialStructureDTOMapper.cs, src/MoBi.Presentation/Mappers/SpatialStructureToSpatialStructureDTOMapper.cs, src/MoBi.Presentation/Presenter/SelectContainerPresenter.cs, src/MoBi.Presentation/Presenter/SelectContanerInTreePresenter.cs, src/MoBi.Presentation/Presenter/SelectNeighborPathPresenter.cs, src/MoBi.Presentation/Presenter/SelectObjectInTreePresenter.cs, src/MoBi.Presentation/Views/ISelectEntityInTreeView.cs, src/MoBi.UI/Views/SelectEntityInTreeView.cs, tests/MoBi.Tests/Presentation/SelectNeighborPathPresenterSpecs.cs
Fixes #1221
The view needs one hierarchical level more to make it easier to find the containers. We are skipping the level of 'SpatialStructure' which is always 1-1 in this view, and often has the name 'Organism'.
So what you get is a top level node for the module, followed by all the top containers in the modules spatial structure.
=> Fixes #1221 For selecting neighbors and containers add the level of node for the building block

src/MoBi.Presentation/Extensions/BreadCrumbExtensions.cs, src/MoBi.Presentation/Presenter/CalculateScaleDivisorsPresenter.cs, src/MoBi.Presentation/Presenter/ExpressionProfileBuildingBlockPresenter.cs, src/MoBi.Presentation/Presenter/IBreadCrumbsPresenter.cs, src/MoBi.Presentation/Presenter/IndividualBuildingBlockPresenter.cs, src/MoBi.Presentation/Presenter/PathAndValueModuleBuildingBlockPresenter.cs, src/MoBi.UI/Views/BasePathAndValueEntityView.cs, src/MoBi.UI/Views/CalculateScaleDivisorsView.cs, src/MoBi.UI/Views/ExpressionProfileBuildingBlockView.cs, src/MoBi.UI/Views/IndividualBuildingBlockView.cs, tests/MoBi.Tests/Presentation/ExpressionProfileBuildingBlockPresenterSpecs.cs, tests/MoBi.Tests/Presentation/IndividualBuildingBlockPresenterSpecs.cs
Fixes #1232
In path and value grids, we are going to automatically show any path element column that has values. Formerly, if there was only one value in a path element column it would be hidden by default.
So, often PathElement 0 would be hidden because it would have one value of the top container 'Organism'. Now we are going to show this column.
We still hide columns that have no values.
=> Fixes #1232 Remove autohide columns in path and value grid views

src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/Commands/AddOutputIntervalCommand.cs, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Presenter/EditOutputSchemaPresenter.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi/MoBi.csproj, tests/MoBi.Tests/Core/Commands/AddOutputIntervalCommandSpecs.cs, tests/MoBi.Tests/Core/Commands/RemoveOutputIntervalCommandSpecs.cs, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Fixes #1227
Fixes #1228
Both were caused by a missing registration of simulation settings during simulation construction as well as missing registration when adding intervals themselves.
There were also no events being used to communicate when an output schema was updated a change in the output intervals collection
=> Fixes #1228 V12: Crash when undoing Output interval modification

src/MoBi.Assets/AppConstants.cs, src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/Domain/Model/MoBiContext.cs, src/MoBi.Core/Domain/UnitSystem/DimensionConverter.cs, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Presenter/EditOutputSelectionsPresenter.cs, src/MoBi.Presentation/Presenter/HierarchicalQuantitySelectionPresenter.cs, src/MoBi.Presentation/Presenter/HierarchicalSimulationPresenter.cs, src/MoBi.Presentation/Presenter/HierarchicalSpatialStructurePresenter.cs, src/MoBi.Presentation/Presenter/HierarchicalStructureEditPresenter.cs, src/MoBi.Presentation/Presenter/HierarchicalStructurePresenter.cs, src/MoBi.Presentation/Tasks/OutputSelectionsTask.cs, src/MoBi.Presentation/Tasks/SimulationCommitTask.cs, src/MoBi.Presentation/Views/IEditOutputSelectionsView.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi.UI/Views/EditOutputSelectionsView.Designer.cs, src/MoBi.UI/Views/EditOutputSelectionsView.cs, src/MoBi.UI/Views/HierarchicalStructureView.cs, src/MoBi/MoBi.csproj, tests/MoBi.Tests/Core/Service/OutputSelectionsTaskSpecs.cs, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/EditOutputSelectionsPresenterSpecs.cs, tests/MoBi.Tests/Presentation/HierarchicalQuantitySelectionPresenterSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Fixes #1163 
Allow users to edit/add/remove selections from the default project settings. In v11 you added/removed/updated these settings by committing from a simulation. We'll add that in #1206. 
This allows users to directly edit the paths in their default simulation settings using a tree browser, or by hand editing the path.
In the simulation settings / output selections tab this grid view has new buttons added to each row
- You can type in the path column to make changes
- If I want to remove, …
=> Fixes #1163 add output selections to project simulation settings editor

src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/Domain/Model/MoBiSpatialStructure.cs, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.UI/MoBi.UI.csproj, src/MoBi/MoBi.csproj, tests/MoBi.Tests/Core/Mapper/ParameterListToSimulationParameterDataTableMapperSpecs.cs, tests/MoBi.Tests/Core/MoBiSpatialStructureSpecs.cs, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/ObjectPathCreatorSpecs.cs, tests/MoBi.Tests/Presentation/Tasks/InitialConditionsTaskSpecs.cs, tests/MoBi.Tests/Presentation/Tasks/ParameterValuesTaskSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Fixes #1285
We were using the wrong overload to append paths together. The extension method first converts the object path to string, then appends the whole string into one element of the object path. So, ```Bone|Intracellular``` was not two elements, but one. 
=> Fixes #1285 Neighborhoods are not exported for compartments

src/MoBi.Assets/AppConstants.cs, src/MoBi.Core/Services/MoleculeResolver.cs, src/MoBi.Presentation/Presenter/BuildingBlockWithInitialConditionsPresenter.cs, src/MoBi.Presentation/Presenter/ExpressionProfileInitialConditionsPresenter.cs, src/MoBi.Presentation/Presenter/InitialConditionsPresenter.cs, src/MoBi.Presentation/Presenter/RefreshInitialConditionsPresenter.cs, src/MoBi.Presentation/Presenter/SelectBuildingBlocksForExtendPresenter.cs, src/MoBi.Presentation/Tasks/Interaction/InitialConditionsTask.cs, src/MoBi.Presentation/Tasks/Interaction/StartValuesTask.cs, src/MoBi.Presentation/Views/IInitialConditionsView.cs, src/MoBi.Presentation/Views/ISelectSpatialStructureAndMoleculesView.cs, src/MoBi.UI/Views/BasePathAndValueEntityView.Designer.cs, src/MoBi.UI/Views/InitialConditionsView.cs, src/MoBi.UI/Views/SelectSpatialStructureAndMoleculesView.cs, tests/MoBi.Tests/Presentation/InitialConditionsPresenterSpecs.cs, tests/MoBi.Tests/Presentation/Tasks/InitialConditionsTaskSpecs.cs
Fixes #1218
Bringing back the previous functionality of refreshing initial conditions from a spatial structure and molecules.
Previously, we always refreshed from the template building blocks, but here the user has to choose what molecules and spatial structure to base their refresh from. That follows the pattern of ```Extend```.
=> Fixes #1218 "Refresh from source" for Initial Conditions

src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Tasks/Edit/EditTaskForContainer.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi/MoBi.csproj, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/Tasks/EditTaskForContainerSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Fixes #1290
This brings back code that exports ```IndividualParameters``` in the container itself when exporting a container with individual and expression. ```ExpressionParameters``` are still exported as ```ParameterValues```
=> Fixes #1290 When loading an organ, individual parameters are not created

src/MoBi.Assets/AppConstants.cs, src/MoBi.Core/Commands/PathAndValueEntityValueOrUnitChangedCommand.cs, src/MoBi.Presentation/Presenter/DistributedPathAndValueEntityPresenter.cs, src/MoBi.Presentation/Presenter/ExpressionDistributedPathAndValueEntityPresenter.cs, src/MoBi.Presentation/Presenter/ExpressionProfileBuildingBlockPresenter.cs, src/MoBi.Presentation/Presenter/IndividualBuildingBlockPresenter.cs, src/MoBi.Presentation/Presenter/InitialConditionsDistributedPathAndValueEntityPresenter.cs, src/MoBi.Presentation/Presenter/ParameterValueDistributedPathAndValueEntityPresenter.cs, src/MoBi.Presentation/Presenter/PathAndValueBuildingBlockPresenter.cs, src/MoBi.Presentation/Tasks/Interaction/InitialConditionsTask.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForExpressionProfileBuildingBlock.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForExtendablePathAndValueEntity.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForIndividualBuildingBlock.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForPathAndValueEntity.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForProjectPathAndValueEntityBuildingBlocks.cs, src/MoBi.Presentation/Tasks/Interaction/ParameterValuesTask.cs, src/MoBi.Presentation/Views/IPathAndValueEntitiesView.cs, src/MoBi.UI/Views/BasePathAndValueEntityView.cs, src/MoBi.UI/Views/DistributedPathAndValueEntityView.Designer.cs, src/MoBi.UI/Views/DistributedPathAndValueEntityView.cs, src/MoBi.UI/Views/ExpressionProfileBuildingBlockView.cs, src/MoBi.UI/Views/IndividualBuildingBlockView.cs, tests/MoBi.Tests/Core/Commands/SetParameterValueWithUnitCommandSpecs.cs, tests/MoBi.Tests/Presentation/IndividualDistributedPathAndValueEntityPresenterSpecs.cs, tests/MoBi.Tests/Presentation/Tasks/InitialConditionsTaskSpecs.cs, tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForExpressionProfileBuildingBlockSpecs.cs, tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForIndividualBuildingBlockSpecs.cs, tests/MoBi.Tests/Presentation/Tasks/ParameterValuesTaskSpecs.cs
Fixes #1291
Changing a distributed parameter will now update the parameter so that it no longer has a distribution type or any sub-parameters in the building block.
The value of the parameter will come from the `MEAN` Subparameter.
When you view a distributed Individual Parameter
Click the edit button converts the parameter to a constant value parameter with the value set to whatever the `MEAN` was before. It also removes sub-parameters from the building block.
This is immediate after pressing edit. …
=> Fixes #1291 Cannot change value of a distributed parameter

src/MoBi.Assets/AppConstants.cs, src/MoBi.Presentation/Mappers/SelectMoleculesDTOMapper.cs, src/MoBi.Presentation/Presenter/SelectBuildingBlocksForExtendPresenter.cs, src/MoBi.Presentation/Presenter/SelectMoleculePresenter.cs, src/MoBi.Presentation/Tasks/Interaction/InitialConditionsTask.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForExtendablePathAndValueEntity.cs, src/MoBi.Presentation/Views/ISelectSpatialStructureAndMoleculesView.cs, src/MoBi.UI/Views/SelectSpatialStructureAndMoleculesView.cs, tests/MoBi.Tests/Presentation/SelectOrganAndProteinsPresenterSpecs.cs, tests/MoBi.Tests/Presentation/SelectSpatialStructureAndMoleculesPresenterSpecs.cs, tests/MoBi.Tests/Presentation/Tasks/InitialConditionsTaskSpecs.cs
Fixes #1322
See the linked issue. We want to hide the spatial structure selection when extending initial conditions because it is not relevant. We also want only to show the molecules that were selected for refresh in the initial conditions building block.
=> Fixes #1322 UX improvements when refreshing initial conditions

src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Tasks/Interaction/InitialConditionsTask.cs, src/MoBi.Presentation/Tasks/ObservedDataTask.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi/MoBi.csproj, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/Tasks/InitialConditionsTaskSpecs.cs, tests/MoBi.Tests/Presentation/Tasks/ObservedDataTasksSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Fixes #1323 
The change checks for usages of a formula in the context of an initial conditions refresh. If all usages of the formula will be replaced with a new formula, then remove the existing formula from the building block cache and add the new formula.
If not all are replaced, the both have to be retained. In that case, the formula being added needs to be renamed if the name is the same as one already present in the formula cache.
=> Fixes #1323 Formula duplicated when updating IC BB

src/MoBi/MoBi.csproj
Fixes #1333
There is a project setting to disable the commit id from the version number attribute
=> Fixes #1333 Commit ID included in version strings

src/MoBi.Presentation/Tasks/ModuleLoader.cs, tests/MoBi.Tests/Presentation/Tasks/ModuleLoaderSpecs.cs
Fixes #1257
Formerly, if the module rename was canceled during import, the empty command was added to the macrocommand, but it was not tested to check if the follow-up commands for expression or individual import should be attempted.
=> #1257 Cancel renaming should also cancel loading exp profiles and individuals

src/MoBi.Presentation/DTO/EventAssignmentBuilderDTO.cs, src/MoBi.Presentation/Mappers/EventAssignmentBuilderToEventAssignmentDTOMapper.cs, src/MoBi.Presentation/Presenter/EditAssignmentBuilderPresenter.cs, src/MoBi.Presentation/Presenter/SelectEventAssignmentTargetPresenter.cs, src/MoBi.Presentation/Views/IEditEventAssignmentBuilderView.cs, src/MoBi.UI/Views/EditEventAssignmentBuilderView.Designer.cs, src/MoBi.UI/Views/EditEventAssignmentBuilderView.cs, src/MoBi.UI/Views/EditParameterView.Designer.cs, src/MoBi.UI/Views/EditParameterView.cs, tests/MoBi.Tests/Presentation/EditAssignmentBuilderPresenterSpecs.cs
Fixes #164. Fixes #1325
@rwmcintosh @PavelBal @Yuri05  
So I am adding a new field to enter the dimension when the path is entered by hand./ This is required because we need to create a "FormulaUsablePath" and not an "ObjectPath" Like in most instances
=> Fixes #164. Fixes #1325

src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForSimulation.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi/MoBi.csproj, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/InteractionTasksForSimulationSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Fixes #1260 
Previously, the task specifically looked for the simulation settings building block version match between the simulation configuration and the project default. Now that's just removed and the tests updated
=> Fixes #1260 Changing output selection adds a red icon to the simulation

src/MoBi.Assets/AppConstants.cs, src/MoBi.Core/Services/BuildingBlockVersionUpdater.cs, tests/MoBi.Tests/Core/BuildingBlockVersionUpdaterSpecs.cs
Fixes #1299
When making any change in a PK-Sim module when the version will be updated, show a dialog to inform the user that the module will not be a PK-Sim module anymore
=> Fixes #1299 Show a warning when converting to extension module

src/MoBi.Presentation/Presenter/SelectLocalisationPresenter.cs
Fixes #1282
The underlying issue was fixed in another commit, but there was still an issue with the dialog because naming the Spatial Structure 'Organism' leads to only a single node created in the view. In this project there are 3 SS with the same name.
=> Fixes #1282 "Local reference point" selection is not working

src/MoBi.Presentation/Tasks/ModuleLoader.cs, tests/MoBi.Tests/Presentation/Tasks/ModuleLoaderSpecs.cs
Fixes #1258
Due to not cloning the incoming simulation transfer, the module was loaded twice with the same Id
=> Fixes #1258 Load simulation twice does not work properly?

src/MoBi.Presentation/Tasks/Interaction/InteractionTask.cs, tests/MoBi.Tests/Presentation/InteractionTasksForSimulationSpecs.cs
Fixes #1261
Formerly this clone for simulation would decode the object type as IObjectBase which would then use "i object base" in the prompt. This changes the type argument in the interaction task so the object type can be decoded properly
=> Fixes #1261 Clone simulation - weird "Rename" dialogue

src/MoBi.Presentation/DTO/ModuleContentDTO.cs, src/MoBi.Presentation/Presenter/AddBuildingBlocksToModulePresenter.cs, src/MoBi.Presentation/Presenter/AddContentToModulePresenter.cs, src/MoBi.Presentation/Presenter/CreateModulePresenter.cs, src/MoBi.Presentation/Views/IAddBuildingBlocksToModuleView.cs, src/MoBi.Presentation/Views/ICreateModuleView.cs, src/MoBi.UI/Views/AddBuildingBlocksToModuleView.cs, src/MoBi.UI/Views/AddContentToModuleView.cs, src/MoBi.UI/Views/BaseModuleContentView.cs, tests/MoBi.Tests/Presentation/AddBuildingBlocksToModulePresenterSpecs.cs, tests/MoBi.Tests/Presentation/CreateModulePresenterSpecs.cs
Fixes #1307
When the user selects the molecules checkbox when creating a module, or when adding molecules to an existing module the checkbox for initial conditions will be automatically selected
=> Fixes #1307 Automatically create a building block "IC" when creating a new Molecules BB

src/MoBi.Assets/AppConstants.cs, src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Presenter/OutputSelectionsPresenter.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForSimulationSettings.cs, src/MoBi.Presentation/UICommand/CommitSimulationOutputSelectionsUICommand.cs, src/MoBi.Presentation/UICommand/CommitSimulationSolverAndSchemaUICommand.cs, src/MoBi.Presentation/Views/IOutputSelectionsView.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi.UI/Views/DefaultOutputSelectionsButtonsView.Designer.cs, src/MoBi.UI/Views/DefaultOutputSelectionsButtonsView.cs, src/MoBi.UI/Views/DefaultOutputSelectionsButtonsView.resx, src/MoBi.UI/Views/OutputSelectionsView.Designer.cs, src/MoBi.UI/Views/OutputSelectionsView.cs, src/MoBi/MoBi.csproj, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/OutputSelectionsPresenterSpecs.cs, tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForSimulationSettingsSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Fixes #1296 
In the 'Define settings and run' dialog, the user can make the selections into project defaults, or load the selections from project defaults. When you create a simulation, the selections would already be project default, but maybe you want to undo some changes you made.
=> 1296 output selections set from project defaults and set as project defaults should be available from define settings and run view

src/MoBi.Presentation/DTO/ObjectBaseDTO.cs, src/MoBi.Presentation/Presenter/HierarchicalSpatialStructurePresenter.cs, src/MoBi.Presentation/Presenter/HierarchicalStructureEditPresenter.cs, src/MoBi.Presentation/Presenter/HierarchicalStructurePresenter.cs, tests/MoBi.Tests/Presentation/HierarchicalSimulationPresenterSpecs.cs, tests/MoBi.Tests/Presentation/HierarchicalSpatialStructurePresenterSpecs.cs
Fixes #1022
When you click on neighbors in the spatial structure view the neighbor node will act as a link to the container that it references. So you can edit the container that the neighbor references when you select the neighbor
=> Fixes #1022

src/MoBi.Presentation/Presenter/EditTableFormulaWithXArgumentFormulaPresenter.cs, src/MoBi.Presentation/Presenter/SelectReferencePresenterBase.cs, src/MoBi.Presentation/Presenter/SelectReferencePresenterFactory.cs
Fixes #1085
In this case, we are editing the formula from the formula cache and do not have the context of what is using the formula. There seems to be some provisions for that and I just made some more so the application will not crash.
I'm not sure if there's another way that would be preferred. Essentially, if you edit from the formula cache, you lose the ability to specify relative paths (it seems). It seems to make sense to me.
For now, I would like a quick comment on whether this approach makes sense, then I'll add some tests for it.
Mark everything that …
=> Fixes #1085 Error when modifying a table formula with x argument

src/MoBi.Presentation/Mappers/NeighborhoodToNeighborDTOMapper.cs, src/MoBi.Presentation/Presenter/HierarchicalSimulationPresenter.cs, src/MoBi.Presentation/Presenter/HierarchicalSpatialStructurePresenter.cs, src/MoBi.Presentation/Presenter/HierarchicalStructureEditPresenter.cs, src/MoBi.Presentation/Presenter/HierarchicalStructurePresenter.cs, tests/MoBi.Tests/Presentation/HierarchicalSimulationPresenterSpecs.cs, tests/MoBi.Tests/Presentation/HierarchicalSpatialStructurePresenterSpecs.cs, tests/MoBi.Tests/Presentation/Mapper/NeighborhoodToNeighborDTOMapperSpecs.cs
Fixes #1284
Adding a node in the simulation editor to show each neighborhood and those nodes will also open the container editor when clicked.
=> Fixes #1284 Show neighbors in the neighborhood view of a simulation

src/MoBi.Presentation/Mappers/StringChangeToSelectDTOStringChangeMapper.cs, src/MoBi.Presentation/Tasks/CheckNameVisitor.cs
Fixes #1312
Changed how the descriptions are created when renaming and added the module name to the title of the window when renaming.
=> #1312 - Rename related entities

appveyor-coverage.yml, appveyor-nightly.yml, appveyor.yml, src/MoBi.Assets/AppConstants.cs, src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/Commands/SetMergeBehaviorCommand.cs, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/DTO/AddBuildingBlocksToModuleDTO.cs, src/MoBi.Presentation/DTO/CloneBuildingBlocksToModuleDTO.cs, src/MoBi.Presentation/DTO/ModuleContentDTO.cs, src/MoBi.Presentation/Mappers/CreateModuleDTOToModuleMapper.cs, src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForModule.cs, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Presenter/AddContentToModulePresenter.cs, src/MoBi.Presentation/Presenter/BaseModuleContentPresenter.cs, src/MoBi.Presentation/Presenter/CloneBuildingBlocksToModulePresenter.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForModule.cs, src/MoBi.Presentation/UICommand/MakeExtendModuleUICommand.cs, src/MoBi.Presentation/UICommand/MakeOverwriteModuleUICommand.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi.UI/Views/BaseModuleContentView.Designer.cs, src/MoBi.UI/Views/BaseModuleContentView.cs, src/MoBi/MoBi.csproj, tests/MoBi.Tests/Core/Commands/SetMergeBehaviorCommandSpecs.cs, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/CloneBuildingBlocksToModulePresenterSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Fixes #1382 
We don't want to refer to a module as having a 'Default' merge behavior, implying it can be overridden.
=> 1382 remove terminology default when referring to merge behavior

src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/Commands/SetMergeBehaviorCommand.cs, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.UI/MoBi.UI.csproj, src/MoBi/MoBi.csproj, tests/MoBi.Tests/Core/Commands/SetMergeBehaviorCommandSpecs.cs, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Fixes #1369 
Added SimulationStatusChangedEvents firing when modifying MergeBehavior, so diff between versions of modules are re-evaluated. Together with an issue-fix in Core ( https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2271 ) to take the mergebehavior into account in the version-hash this results in a correct sync-no sync indicator. 
When the module is set to extend: 
the simulation-view looks like this:
=> #1369 Changing the "Merge behavior" of a module should mark the simulation as "not synched"

src/MoBi.Presentation/Presenter/SelectLocalisationPresenter.cs, tests/MoBi.Tests/Presentation/SelectLocalisationPresenterSpecs.cs
Fixes #1282
This probably stopped working because we introduced a new node type into the view. Now it's possible to have containers at the top, but also spatial structures.
=> Fixes #1282

src/MoBi.Presentation/Presenter/EditParametersInContainerPresenter.cs, src/MoBi.Presentation/Views/IEditParametersInContainerView.cs, src/MoBi.UI/Views/EditParametersInContainerView.cs, tests/MoBi.Tests/Presentation/EditParameterListSpecs.cs
Fixes #1364
Add new default label when containter is unnamed
=> #1364 new passive transport default label when unnamed

src/MoBi.Presentation/Presenter/EditBuildingBlockPresenterBase.cs, src/MoBi.Presentation/Presenter/HierarchicalStructureEditPresenter.cs, src/MoBi.UI/Views/EditSpatialStructureView.cs, tests/MoBi.Tests/Presentation/EditSpatialStructureViewSpecs.cs
Fixes #1424 
Selecting a neighbor in the neighborhood view: behavior when the container is not present in the module should be not to show it.
=> #1424 Selecting a neighbor not present should remove view

src/MoBi.Assets/AppConstants.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForSimulationSettings.cs, src/MoBi.Presentation/Tasks/ProjectTask.cs, tests/MoBi.Tests/Presentation/ProjectTaskSpecs.cs
Fixes #1442
When importing a simulation from PK-Sim, set the project-wide simulation settings
=> #1442 when importing a simulation set project simulation settings

src/MoBi.Assets/AppConstants.cs, src/MoBi.Presentation/MenusAndBars/ContextMenus/RootContextMenuForSpatialStructure.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForSpatialStructure.cs, src/MoBi.Presentation/UICommand/AddCommandFor.cs, tests/MoBi.Tests/Presentation/ObjectBaseDTOSpecs.cs
Fixes #1461 - I assume "Events" is a valid name for any object now. I don't think it needs to be reserved.
Removing "Events" as an unusable name for objects
=> Fixes  #1461 Cannot create a top level container "Events"

src/MoBi.Assets/AppConstants.cs, src/MoBi.Core/Services/TemplateResolverTask.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForModule.cs, tests/MoBi.Tests/IntegrationTests/InteractionTasksForModuleSpecs.cs
Fixes #1464
We were not checking if modules are used before removing them if the task was initiated with a multiple module context menu.
=> Fixes #1464

src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForSimulation.cs, src/MoBi.Presentation/UICommand/CloneSimulationUICommand.cs
Fixes #1488
When the simulation is cloned, it should be opened in the configuration editor. Most likely the user is trying to make some changes to the clone and this saves a click or two in the workflow
=> Fixes #1488 "Clone" simulation should show the configuration dialog

src/MoBi.Assets/AppConstants.cs, src/MoBi.Presentation/Tasks/ProjectTask.cs, tests/MoBi.Tests/Presentation/ProjectTaskSpecs.cs
Fixes #1442
No more prompting for subsequent simulation loads whether the user wants to update default simulations
=> Fixes #1442

src/MoBi.Presentation/Presenter/EditTableFormulaWithOffSetFormulaPresenter.cs, src/MoBi.Presentation/Presenter/EditTableFormulaWithXArgumentFormulaPresenter.cs, src/MoBi.Presentation/Presenter/SelectReferenceAtParameterPresenter.cs, tests/MoBi.Tests/Presentation/EditTableFormulaWithOffSetFormulaPresenterSpecs.cs, tests/MoBi.Tests/Presentation/EditTableFormulaWithXArgumentFormulaPresenterSpecs.cs, tests/MoBi.Tests/Presentation/SelectReferenceAtParameterPresenterSpecs.cs
Fixes #1521
Remove time as a selectable reference for TableFormulaWithXArgument
=> Fixes #1521 "TIME" cannot be selected as x-argument of table formula with x argument

src/MoBi.Core/Services/SimulationLoader.cs, src/MoBi.Presentation/Presenter/Main/ModuleExplorerPresenter.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTaskFor.cs, tests/MoBi.Tests/Core/SimulationLoaderSpecs.cs
Fixes #1529 
We made the decision at some point to edit modules when they are added to the project if they only have a single building block. This probably should not be done when the modules are being added from PKML though, either when loading a simulation and creating the modules, or just loading the modules from a simulation (without the simulation).
=> Fixes #1529 When loading a simulation, some building block is automatically opened.

src/MoBi.Presentation/Presenter/CreateObjectPathsFromReferencesPresenter.cs, src/MoBi.Presentation/Presenter/SelectReferenceAtParameterValuePresenter.cs, src/MoBi.Presentation/Presenter/SelectReferencePresenterBase.cs, src/MoBi.UI/Views/CreateObjectPathsFromReferencesView.cs, tests/MoBi.Tests/Presentation/CreateObjectPathsFromReferencesPresenterSpecs.cs, tests/MoBi.Tests/Presentation/SelectReferenceAtParameterValuePresenterSpecs.cs
Fixes #1508 
Adding expressions and individuals as selectable elements in the New PathAndValueEntity object path selection dialog.
See the screenshot. The tree nodes relating to individuals and expressions do not have icons because these are reconstructed from paths. There's no other context for icons.
=> Fixes #1508 PV BB -> New Parameter Value: also show parameters from ExpProfiles and Individuals

src/MoBi.Assets/AppConstants.cs, src/MoBi.Core/Commands/AddPathAndValueEntityToBuildingBlockCommand.cs, src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForInitialConditionsBuildingBlock.cs, src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForParameterValuesBuildingBlock.cs, src/MoBi.Presentation/Tasks/Interaction/IInteractionTasksForExtendablePathAndValueEntity.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForExtendablePathAndValueEntity.cs, src/MoBi.Presentation/UICommand/ExtendParameterValuesFromPathAndValuesUICommand.cs
Fixes #1415
Add a convenient way for users to import path and values into various building blocks.
- Import individual pkml into pvbb
- Import expression pkml into pvbb
- Import ic pkml into ic
=> Fixes #1415 Extend PV and IC BB from PKML

src/MoBi.Presentation/Tasks/Edit/EditTaskFor.cs, tests/MoBi.Tests/Presentation/Tasks/EditTasksForBuildingBlockSpecs.cs
Fixes #1467
Renaming a building block should not trigger "Rename related entities"
=> #1467 renaming  building block

src/MoBi.Core/Commands/BuildingBlockChangeCommandBase.cs, tests/MoBi.Tests/Core/MoBiContextSpecs.cs
Fixes #1563
Renaming uses commands for building blocks, but when renaming non-building block items, the property is left null. 
=> Exception when trying to rename a simulation #1563

src/MoBi.UI/Views/IndividualBuildingBlockView.cs
Fixes #1568
We have to remove the old controls for origindata when editing an individual. The view is sometimes already visible when the item is double clicked or edited.
=> Two individual in MoBi: Keep switching between them #1568

src/MoBi.UI/Views/BasePathAndValueEntityView.cs, src/MoBi.UI/Views/ParameterValuesView.cs
Fixes #1562
Show column chooser and only allow context menu for empty context (not when clicking in headers or cells)
=> Fixes #1562 PV BB: right clicking on a column name shows two context menus

src/MoBi.Assets/AppConstants.cs, src/MoBi.Core/Commands/UpdateSimulationCommand.cs, src/MoBi.Core/Events/ShowSimulationChangesEvent.cs, src/MoBi.Core/Serialization/Xml/Serializer/OriginalQuantityValueXmlSerializer.cs, src/MoBi.Presentation/DTO/OriginalQuantityValueDTO.cs, src/MoBi.Presentation/Formatters/FormatterExtensions.cs, src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForSimulation.cs, src/MoBi.Presentation/Presenter/EditSimulationPresenter.cs, src/MoBi.Presentation/Presenter/SimulationChangesPresenter.cs, src/MoBi.Presentation/UICommand/ShowChangesUICommand.cs, src/MoBi.Presentation/UICommand/ShowDifferencesUICommand.cs, src/MoBi.Presentation/Views/IEditSimulationView.cs, src/MoBi.Presentation/Views/ISimulationChangesView.cs, src/MoBi.UI/Views/SimulationChangesView.Designer.cs, src/MoBi.UI/Views/SimulationChangesView.cs, src/MoBi.UI/Views/SimulationChangesView.resx, src/MoBi.UI/Views/SimulationView/EditSimulationView.Designer.cs, src/MoBi.UI/Views/SimulationView/EditSimulationView.cs, tests/MoBi.Tests/Core/Service/SimulationUpdateTaskSpecs.cs, tests/MoBi.Tests/Presentation/EditSimulationPresenterSpecs.cs
Fixes #1083
There is very little new interaction in this fix. A context menu was added to show the differences tab. The tab is also updated when it is selected by the user. There is no edits that can occur in the view, it's readonly
=> Fixes #1083 Simulation out of synch - show differences

src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForInitialConditionsFolder.cs, src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForParameterValuesFolder.cs, src/MoBi.Presentation/Tasks/Interaction/InitialConditionsTask.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTaskFor.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForExpressionProfileBuildingBlock.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForModule.cs, src/MoBi.Presentation/Tasks/Interaction/ParameterValuesTask.cs, src/MoBi.Presentation/UICommand/AddInitialConditionsBuildingBlockCommand.cs, src/MoBi.Presentation/UICommand/AddParameterValuesBuildingBlockCommand.cs, tests/MoBi.Tests/IntegrationTests/InteractionTasksForModuleSpecs.cs, tests/MoBi.Tests/Presentation/Tasks/InteractionTasksForModuleSpecs.cs
Fixes #1585
We don't need to check all the imports for name uniqueness because most imported building blocks are only allowed to be present once in a module.
That's not the case for initial conditions and parameter values. The names have to be checked before adding
=> Fixes #1585 Possible to load a PV BB with the same name as an existing

src/MoBi.Core/Services/SimulationLoader.cs, tests/MoBi.Tests/Core/SimulationLoaderSpecs.cs
Fixes #1554 
When importing a simulation from pkml, whose name already exists in the project: MoBi asks to rename the simulation and suggests <old simulation name> N as the new default name:
However, if I enter another name for the simulation: the module of the imported simulation still has the default name
=> #1554 rename module

src/MoBi.UI/Views/EditIndividualAndExpressionConfigurationsView.cs
Fixes #1600
UI does not update selected nodes when first binding. If you have more than one expression, then click on one, then the other forces the UI update, but if you have only one, there is no opportunity to force the event to fire.
=> Fixes #1600 Cannot select a protein from expression panel when only one expression is available

src/MoBi.Presentation/Presenter/SimulationChangesPresenter.cs, tests/MoBi.Tests/Presentation/SimulationChangesPresenterSpecs.cs
Fixes #1607
We can't resolve entities that have been changed outside the model root. When the user is shown the simulation changes, we can show only the changes from the model (not changes in output selections or schema)
=> Fixes #1607 Changes for non-model properties cause simulation to crash

src/MoBi.Presentation/Presenter/SelectNeighborPathPresenter.cs, tests/MoBi.Tests/Presentation/SelectNeighborPathPresenterSpecs.cs
Fixes #1579
Formerly you could only select existing physical containers in this view, but now you can select any container, and as well, you can hand edit the paths and still create the neighborhood
=> Fixes #1579 Create a neighborhood: "OK" button should be enabled as soon as both paths are specified

src/MoBi.Presentation/Presenter/EditEventGroupBuildingBlockPresenter.cs, src/MoBi.Presentation/Presenter/EventGroupListPresenter.cs, src/MoBi.Presentation/Views/IEventGroupsListView.cs, src/MoBi.UI/Views/EventGroupsListView.cs, tests/MoBi.Tests/Presentation/EventGroupListPresenterSpecs.cs
Fixes #1611
Previously there was no selectivity for which events building block was being edited so all editors would refresh on removing an event builder. So selectivity is added here.
Also added - we don't re-edit the whole building block on event response, but selectively add/remove items in the tree view in response.
=> Fixes #1611 Weird refresh of events tree view

src/MoBi.Presentation/Presenter/ParameterValuesPresenter.cs, tests/MoBi.Tests/Presentation/ParameterValuesPresenterSpecs.cs
Fixes #1526
Always reinitialize columns if the user adds a new PV with a longer path length
=> Fixes #1526 PV BB: New parameter value - required columns are not added

src/MoBi.Core/Commands/RenameModelCommand.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForSimulation.cs, tests/MoBi.Tests/Presentation/InteractionTasksForSimulationSpecs.cs
Fixes #1626
Cloning a simulation left the old name on the model and the root container
=> Fixes #1626 Cloning a simulation should rename the Model and the Root

src/MoBi.Presentation/Presenter/MoBiMainViewPresenter.cs
Fixes #221 
Implements feature request to show the active project name in the application title bar. This helps users identify the correct MoBi instance when multiple projects are open.
- Added ProjectLoadedEvent and ProjectClosedEvent handlers to IMoBiMainViewPresenter
- Implemented window title updates on project load/close
- Uses format: "MoBi® 12 | ProjectName" when project is loaded
- Maintains default title "MoBi® 12" when no project is open
- Verified title updates when loading a project
- Verified title reverts when closing a project
- Verified correct display in Windows taskbar
- multiple windows open: 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list …
=> #221 show project file name in the title bar

src/MoBi.Core/Services/SimulationLoader.cs, tests/MoBi.Tests/Core/SimulationLoaderSpecs.cs
Fixes #1640
This covers the case where you load a simulation and there are colliding modules, but no colliding simulation to trigger a rename of the modules
=> Fixes #1640 Cannot load a simulation after renaming any simulation

src/MoBi.Presentation/UICommand/AddNewBuildingBlockCommand.cs, src/MoBi.Presentation/UICommand/AddNewExpressionProfileBuildingBlock.cs, src/MoBi.Presentation/UICommand/AddNewIndividualCommand.cs
Fixes #1649
Most UI commands clear the `Subject` after they complete. These particular ones use a static subject to outline what type of object should be imported
=> Fixes #1649 Cannot import Expressions from PK-Sim more than once

src/MoBi.Presentation/Presenter/SelectMoleculePresenter.cs, src/MoBi.Presentation/Views/ISelectMoleculeView.cs, src/MoBi.UI/Views/SelectMoleculesView.cs, tests/MoBi.Tests/Presentation/SelectMoleculesPresenterSpecs.cs
Fixes #1642
This way we are much more surgical about how validations on non-focused rows are happening.
Formerly refreshdata expanded all the rows each time you selected/unselected a molecule
=> Fixes #1642

src/MoBi.Core/Extensions/PathAndValueEntityExtensions.cs, src/MoBi.Presentation/Mappers/PathAndValueEntityBuildingBlockToPathAndValueEntityBuildingBlockDTOMapper.cs, src/MoBi.Presentation/Presenter/SelectReferenceAtParameterValuePresenter.cs, tests/MoBi.Tests/Presentation/SelectReferenceAtParameterValuePresenterSpecs.cs
Fixes #1668
Fixes #1666
Same fix for both. The problem in 1666 was that the parameter had been converted from a distributed parameter to non-distributed. Then when trying to show a sub-parameter like `Mean` we could not add a container for it because it would have been called `Volume`, however, there's already an object with that name.
So, by hiding sub-parameters we fix both these issues.
=> Fixes #1666 V12: Cannot create new parameter value

src/MoBi.Assets/AppConstants.cs, src/MoBi.Core/Commands/AddBuildingBlockToModuleCommand.cs, src/MoBi.Core/Commands/BuildingBlockChangeCommandBase.cs, src/MoBi.Core/Commands/IWillConvertPKSimModuleToExtensionModule.cs, src/MoBi.Core/Commands/ModuleContentChangeCommandExtensions.cs, src/MoBi.Core/Commands/ModuleContentChangedCommand.cs, src/MoBi.Core/Commands/RemoveBuildingBlockFromModuleCommand.cs, src/MoBi.Core/Domain/Model/MoBiContext.cs, src/MoBi.Core/Services/BuildingBlockVersionUpdater.cs, src/MoBi.Presentation/Presenter/Main/ModuleExplorerPresenter.cs, tests/MoBi.Tests/Core/Commands/AddBuildingBlockToModuleCommandSpecs.cs, tests/MoBi.Tests/Core/Commands/MoveBuildingBlockToModuleCommandSpecs.cs, tests/MoBi.Tests/Core/Commands/RemoveBuildingBlockFromModuleCommandSpecs.cs
=> Fixes #1659 Removing Initial Conditions or Parameter Valuesfrom PK-Sim module does not ask for changing to extension module

src/MoBi.Core/Commands/RenameContainerCommand.cs, tests/MoBi.Tests/Core/Commands/RenameContainerCommandSpecs.cs
Fixes #1679
There are now separate commands to change the related neighborhood paths that the user can select when renaming a container. The neighborhood paths should not be updated by the container rename command now.
=> Fixes #1679 v12: "Rename related entities" always applied for neighborhoods?

src/MoBi.Core/Domain/Model/MoBiContext.cs, tests/MoBi.Tests/Core/MoBiContextSpecs.cs
Fixes #1653
For modules not contained by the project, a prompt will not be shown when a command is used to modify them. This is probably only the case when we are adding/removing ic/pv during commit/update operations
=> Fixes #1653 "Convert to extension module" prompt comes 2 times

src/MoBi.Presentation/Presenter/ObjectPathCreatorAtTransport.cs, tests/MoBi.Tests/Presentation/ObjectPathCreatorAtTransportSpecs.cs
Fixes #1619 
Creation of reference path for passive is not woring as expected
=> #1619 Creation of reference path for passive is not woring as expected

src/MoBi.Assets/AppConstants.cs, src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/DTO/SimulationDTO.cs, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Presenter/CreateSimulationConfigurationPresenter.cs, src/MoBi.Presentation/Views/ICreateSimulationConfigurationView.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi.UI/Views/CreateSimulationConfigurationView.Designer.cs, src/MoBi.UI/Views/CreateSimulationConfigurationView.cs, src/MoBi/MoBi.csproj, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Fixes #1606
This is just an update that exposes an option to create all process rate parameters for a simulation during simulation creation
=> Fixes #1606 Create process option when configuring a simulation

src/MoBi.Assets/AppConstants.cs, src/MoBi.Core/Commands/SetContainerModeCommand.cs, src/MoBi.Presentation/Presenter/EditContainerPresenter.cs, src/MoBi.Presentation/Tasks/Edit/EditTaskFor.cs, src/MoBi.Presentation/Tasks/Edit/EditTaskForContainer.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTaskFor.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForContainer.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForContainerBase.cs, src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForTopContainer.cs, src/MoBi.UI/Views/EditContainerView.cs, tests/MoBi.Tests/Presentation/EditContainerPresenterSpecs.cs
Fixes #1678
Logical containers containers should not have molecule properties.
When switching modes it should either create or alert and remove the molecule properties
=> 1678 v12 logical containers should not have moleculeproperties

src/MoBi.UI/Settings/UserSettings.cs
Fixes #1703 
Occasionally an error occurs when serializing layout data to the user settings in MoBi. This is a patch that checks if the dock windows were all removed when the settings were restored. If so, we re-apply the defaults.
It's a bit of a patch, because we don't know why the XML is corrupted in the first place, so I don't know if it's really a 'Bug **Fix**'.
=> Fixes #1703 Corrupted settings.xml causes empty MoBi screen

src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.Presentation/Presenter/EditIndividualAndExpressionConfigurationsPresenter.cs, src/MoBi.Presentation/Presenter/EditModuleConfigurationsPresenter.cs, src/MoBi.Presentation/Presenter/Main/ModuleExplorerPresenter.cs, src/MoBi.Presentation/Presenter/Main/SimulationExplorerPresenter.cs, src/MoBi.UI/MoBi.UI.csproj, src/MoBi/MoBi.csproj, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/ModuleExplorerPresenterSpecs.cs, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Fixes #1721 
We did not prevent users from moving building blocks by drag and drop when the module was used by a simulation.
By preventing this, it made sense to make a distinction between move and copy in the drag effects.
=> 1721 drag drop of building blocks between modules

src/MoBi.Presentation/Tasks/Edit/EditTaskForContainer.cs, tests/MoBi.Tests/Presentation/Tasks/EditTaskForContainerSpecs.cs
Fixes #1711
We made it the default from `SpatialStructureFactory` that an `Events` container is always added. In this special case, we don't want this container during export.
=> Fixes #1711 "Events" container is exported every time any container is exported to PKML?

src/MoBi.Assets/AppConstants.cs
Fixes #1716 
Clarify thet the PV are always added in the last module
=> #1716 Clarify thet the PV are always added in the last module

src/MoBi.Presentation/Mappers/SpatialStructureToSpatialStructureDTOMapper.cs, src/MoBi.Presentation/Presenter/SelectEventAssignmentTargetPresenter.cs, tests/MoBi.Tests/Presentation/SelectEventAssingmentTargetPresenterSpecs.cs
Fixes #1761
Spatial structures were not added to this view as they were in V11.
Should Events and MoleculeProperties be shown in this view?
=> Fixes #1761 Cannot select changed entities in event assignments

src/MoBi.Presentation/Presenter/EditFormulaPresenter.cs, tests/MoBi.Tests/Presentation/EditFormulaInPathAndValuesPresenterSpecs.cs
=> Fixes #1774 Exception after entering the name of new reaction or passive transport

src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.Presentation/Presenter/EditFormulaInContainerPresenter.cs, src/MoBi.Presentation/Presenter/EditFormulaPathListPresenter.cs, src/MoBi/MoBi.csproj, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.Tests/Presentation/EditExplicitFormulaPresenterSpecs.cs, tests/MoBi.Tests/Presentation/EditFormulaPathListPresenterSpecs.cs
Fixes #1045
Fixes #509
When adding a new alias in an explicit formula it was possible to crash MoBi on a stack overflow exception.
This is just an explicit check to make sure that the new path does not create a circular reference. The exception throw is the same as the strategy when creating a new parameter.
This fixes both issues because we are catching the circular reference at the stage where the path is entered, which is common to creating or editing a parameter formula. You will not be able to enter the value like this as described in the issue.
The exception is thrown for a different parameter name, but the dialog is shown and then the value is cleared
Please describe the tests that you ran to verify your changes. Provide …
=> Fixes #1045 Silent crash when creating a circular reference

src/MoBi.Assets/AppConstants.cs, src/MoBi.Core/Commands/EditParameterCanBeVariedCommand.cs, src/MoBi.Presentation/DTO/ParameterDTO.cs, src/MoBi.Presentation/Presenter/EditParameterPresenter.cs, src/MoBi.UI/Views/EditParameterView.Designer.cs, src/MoBi.UI/Views/EditParameterView.cs, tests/MoBi.Tests/Core/Commands/EditParameterCanBeVariedCommandSpecs.cs, tests/MoBi.Tests/Core/Commands/EditParameterCanBeVariedInPopulationCommandSpecs.cs, tests/MoBi.Tests/Core/Mapper/ApplicationBuilderToDTOApplicationBuilderMapperSpecs.cs, tests/MoBi.Tests/Presentation/EditParameterPresenterSpecs.cs
Fixes #294 Parameter CanBeVaried can be edited in MoBi
Exposing a property in the edit parameter view
=> Fixes #294 Parameter CanBeVaried flag should be editable in MoBi

src/MoBi.Core/Services/ParameterAnalysableParameterSelector.cs, tests/MoBi.Tests/Core/ParameterAnalysableParameterSelectorSpecs.cs
Fixes #1792
Disable selectability of distributed sub-parameters
=> Fixes #1792 Mean/Deviation/Percentile parameters are selectable in PI/SA

src/MoBi.Assets/AppConstants.cs, src/MoBi.Presentation/Tasks/MoBiFormulaTask.cs, tests/MoBi.Tests/Presentation/Tasks/MoBiFormulaTaskSpecs.cs
Fixes #1702
A `FormulaUsablePath` has to be converted to a `TimePath` if the dimension and path are set up correctly through the editor. That's because `TimePath` overrides the `Resolve` method of `ObjectPath`
The reverse is also true if a dimension or path is adjusted on a `TimePath`
=> Fixes #1702 "Time" not recognized in newly build formula

src/MoBi.Presentation/UICommand/RenameFromContextMenuCommand.cs, src/MoBi.UI/Views/BaseModuleContentView.Designer.cs, src/MoBi.UI/Views/BaseModuleContentView.cs
Fixes #1732
Reorder between `molecules` and `reactions` when you modify a module (add/create) and change the type from `Event` to `Events`.
=> Fixes #1732 Consistent naming of Building Blocks

src/MoBi.Presentation/Presenter/EditIndividualAndExpressionConfigurationsPresenter.cs
Fixes #1874
Must have been from DevExpress update
=> Fixes #1874 Cannot add expression profiles to new simulation

src/MoBi.Presentation/Presenter/EditFormulaPathListPresenter.cs, tests/MoBi.Tests/Presentation/EditFormulaPathListPresenterSpecs.cs
Fixes #1909
There are cases where the circular reference checker should not be used. RHS is one case.
=> Fixes #1909 RHS in spatial structure circular reference not allowed

src/MoBi.Presentation/Presenter/EditParametersInContainerPresenter.cs, tests/MoBi.Tests/Presentation/EditParametersInContainerPresenterSpecs.cs
Fixes #1880
When the parameter is a preview of an individual parameter we have to get the path a different way
=> Fixes #1880 Show parameters from Individual/Copy Path: only parametername is copied.

src/MoBi.Presentation/Presenter/EditContainerPresenter.cs, tests/MoBi.Tests/Presentation/EditContainerPresenterSpecs.cs
Fixes #1984
We set the mode, but do not add the MoleculeProperties container when the container is new.
=> Creating a new physical container does not create "MoleculeProperties" node

src/MoBi.Assets/AppConstants.cs, src/MoBi.Presentation/Tasks/ProjectTask.cs, tests/MoBi.Tests/Presentation/ProjectTaskSpecs.cs
Fixes #1962
User confirmation that export should proceed when a project has PK-Sim modules that do not contain a snapshot
=> Fixes #1962 Warning for pksim modules that don't have a pksim snapshot

src/MoBi.Core/Services/ISimulationRunner.cs, src/MoBi.Presentation/Presenter/Main/MenuAndToolBarPresenter.cs, src/MoBi.Presentation/Tasks/SimulationRunner.cs, tests/MoBi.Tests/Presentation/Tasks/SimulationRunnerSpecs.cs
Fixes #2008
When starting >1 simulation runs in parallel: STOP button is deactivated after the 1st simulation run is finished
=> #2008 when starting 1 simulation in paralell

src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForInitialConditionsBuildingBlock.cs, src/MoBi.Presentation/Tasks/SerializationTask.cs, src/MoBi.Presentation/UICommand/ExtendInitialConditionsFromExpressionProfileUICommand.cs, src/MoBi.Presentation/UICommand/ExtendParameterValuesFromPathAndValuesUICommand.cs
Fixes #2030 Initial conditions BB - Extend from BB and select an Expression Profile
Fixes #2031 Load Initial Conditions BB - select an exported Expression Profile
Serializer accepted non-matching xml elements because of a bug in the serialization task.
Allow users to extend initial conditions from expression profile because it contains initial conditions.
=> Issues while importing initial conditions

src/MoBi.Core/Commands/SynchronizeParameterValueCommand.cs, tests/MoBi.Tests/Core/Commands/SynchronizeParameterValueCommandSpecs.cs
Fixes #1966
1. In a simulation, change the value of e.g. Organism|Age parameter from 30 to 31 years.
2. Commit simulation to building blocks
3. In the simulation, change the value for the same parameter again, e.g. from 31 to 32 years.
4. Commit simulation to building blocks.
5. In the history, try to roll back to the state before changing the parameter value
This Crashes the whole system.
=> #1966 rollback crashes.

src/MoBi.Presentation/UICommand/LoadModuleFromSnapshotUICommand.cs
Fixes #2047
The UI looks a bit messy when you have the name correction dialog open before the heavy work scroller is closed
=> Fixes #2047 Separate snapshot creation from loading

src/MoBi.Assets/MoBi.Assets.csproj, src/MoBi.BatchTool/MoBi.BatchTool.csproj, src/MoBi.CLI.Core/CLIRegister.cs, src/MoBi.CLI.Core/MoBi.CLI.Core.csproj, src/MoBi.CLI.Core/RunOptions/MoBiQualificationRunOptions.cs, src/MoBi.CLI.Core/Services/QualificationRunner.cs, src/MoBi.CLI/MoBi.CLI.csproj, src/MoBi.CLI/QualificationRunCommand.cs, src/MoBi.Core/MoBi.Core.csproj, src/MoBi.Core/Services/PKSimStarter.cs, src/MoBi.Engine/MoBi.Engine.csproj, src/MoBi.Presentation/MoBi.Presentation.csproj, src/MoBi.R/MoBi.R.csproj, src/MoBi.UI/MoBi.UI.csproj, src/MoBi/MoBi.csproj, tests/MoBi.HelpersForTests/MoBi.HelpersForTests.csproj, tests/MoBi.Tests/CLI/QualificationRunnerSpecs.cs, tests/MoBi.Tests/MoBi.Tests.csproj, tests/MoBi.UI.Tests/MoBi.UI.Tests.csproj
Fixes #2090
Option to override user settings for PK sim exe path during qualification.
=> Fixes #2090 add pk-sim path as argument to CLI
